/*
  Copyright (c) 2010-2025, Intel Corporation
  SPDX-License-Identifier: BSD-3-Clause
*/

#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <algorithm>
#include <string>
#include <vector>
#include <chrono>
#include <mutex>
#include <sstream>
#include <iomanip>
#include <atomic>
#include <arpa/inet.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <signal.h>
#include <unistd.h>
#include <string.h>
using namespace std;

// Include ISPC header (generated by the ISPC compiler)
#include "simple_ispc.h"
using namespace ispc;


constexpr int MAX_POST_LEN = 128;
constexpr int MAX_RESULTS = 16;

constexpr int N = 5;  // number of posts

int main() {
    // ---------------------------------------------------------
    // 1️⃣  Machine ID (like MAC hash)
    // ---------------------------------------------------------
    const char* machine_id_str = "abc";  // example ID
    uint8_t machine_id[16] = {};
    int machine_len = strlen(machine_id_str);
    strncpy((char*)machine_id, machine_id_str, machine_len);

    // ---------------------------------------------------------
    // 2️⃣  Initialize post map
    // ---------------------------------------------------------
    PostMap map{};
    map.next_slot = 0;

    // ---------------------------------------------------------
    // 3️⃣  Prepare users and post texts
    // ---------------------------------------------------------
    int user_ids[N] = {1, 2, 1, 3, 2};
    const char* texts[N] = {
        "Hello world from user1",
        "GPU programming is cool",
        "Another post by user1",
        "ISPC parallelism rocks!",
        "Final post from user2"
    };

    // Flatten post texts
    std::vector<uint8_t> post_texts(N * MAX_POST_LEN);
    for (int i = 0; i < N; i++)
        strncpy((char*)&post_texts[i * MAX_POST_LEN], texts[i], MAX_POST_LEN);

    // post_ids can be left empty — kernel will generate unique IDs internally
    std::vector<int64_t> post_ids(N, 0);

    // ---------------------------------------------------------
    // 4️⃣  Launch ISPC kernel
    // ---------------------------------------------------------
    std::cout << "\n=== Creating Posts ===\n";
    ispc::newPost_batch(map,
                        machine_id,
                        machine_len,
                        user_ids,
                        post_texts.data(),
                        post_ids.data(),
                        N);

    // ---------------------------------------------------------
    // 5️⃣  Print results (verify posts stored)
    // ---------------------------------------------------------
    std::cout << "\n=== PostMap contents ===\n";
    for (int i = 0; i < map.next_slot; i++) {
        std::cout << "[" << i << "] "
                  << "user_id=" << map.posts[i].user_id
                  << "  post_id=" << map.posts[i].post_id
                  << "  text=" << map.posts[i].post_string
                  << "\n";
    }

    std::cout << "----------------------------------------\n";
constexpr int Q = 4;  // number of users we’ll query
    int query_user_ids[Q] = {1, 2, 3, 4};  // includes a missing one (4)

    std::vector<uint8_t> out_posts(Q * MAX_RESULTS * MAX_POST_LEN);
    std::vector<int> out_counts(Q, 0);

    // ---------------------------------------------------------
    // 7️⃣ Run lookup kernel
    // ---------------------------------------------------------
    std::cout << "\n=== Running getPostByUser_batch() ===\n";
    ispc::getPostByUser_batch(map,
                              query_user_ids,
                              Q,
                              out_posts.data(),
                              out_counts.data());

    // ---------------------------------------------------------
    // 8️⃣ Print lookup results
    // ---------------------------------------------------------
    std::cout << "\n=== Lookup Results ===\n";
    for (int i = 0; i < Q; i++) {
        std::cout << "User " << query_user_ids[i]
                  << " → " << out_counts[i] << " posts\n";

        for (int j = 0; j < out_counts[i]; j++) {
            const char *post_txt =
                (const char *)&out_posts[(i * MAX_RESULTS + j) * MAX_POST_LEN];
            std::cout << "   " << post_txt << "\n";
        }
        std::cout << "-----------------------------------\n";
    }
    std::cout << "Done.\n";
    return 0;
}