/*
  Copyright (c) 2010-2025, Intel Corporation
  SPDX-License-Identifier: BSD-3-Clause
*/

#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <algorithm>
#include <string>
#include <vector>
#include <chrono>
#include <mutex>
#include <sstream>
#include <iomanip>
#include <atomic>
#include <arpa/inet.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <signal.h>
#include <unistd.h>
#include <string.h>
using namespace std;

// Include ISPC header (generated by the ISPC compiler)
#include "simple_ispc.h"
using namespace ispc;

#include <sys/socket.h>
#include <signal.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
using namespace std;


 
 
 static int64_t current_timestamp = -1;
//static int counter = 0;
std::string machine_id;
std::mutex _thread_lock;
	  
static	  std::atomic<int> counter{0};


#define CUSTOM_EPOCH 1514764800000

using std::chrono::milliseconds;
using std::chrono::duration_cast;
using std::chrono::system_clock;

static int GetCounter(int64_t timestamp) {
  if (current_timestamp > timestamp) {
    cout << "Timestamps are not incremental."<<endl;
    exit(EXIT_FAILURE);
  }
  if (current_timestamp == timestamp) {
    return counter++;
  } else {
	  _thread_lock.lock();
    current_timestamp = timestamp;
    counter = 0;
	_thread_lock.unlock();
    return counter++;
  }
}

int64_t UploadUniqueId(
	int64_t req_id
	) 
	{

  int64_t timestamp = duration_cast<milliseconds>(
      system_clock::now().time_since_epoch()).count() - CUSTOM_EPOCH;
  //
  int idx = GetCounter(timestamp);

  std::stringstream sstream;
  sstream << std::hex << timestamp;
  std::string timestamp_hex(sstream.str());

  if (timestamp_hex.size() > 10) {
    timestamp_hex.erase(0, timestamp_hex.size() - 10);
  } else if (timestamp_hex.size() < 10) {
    timestamp_hex = std::string(10 - timestamp_hex.size(), '0') + timestamp_hex;
  }

  // Empty the sstream buffer.
  sstream.clear();
  sstream.str(std::string());

  sstream << std::hex << idx;
  std::string counter_hex(sstream.str());

  if (counter_hex.size() > 3) {
    counter_hex.erase(0, counter_hex.size() - 3);
  } else if (counter_hex.size() < 3) {
    counter_hex = std::string(3 - counter_hex.size(), '0') + counter_hex;
  }
  std::string post_id_str = machine_id + timestamp_hex + counter_hex;
  int64_t post_id = stoul(post_id_str, nullptr, 16) & 0x7FFFFFFFFFFFFFFF;
  //cout << "The post_id of the request "
  //    << req_id << " is " << post_id<<endl;
	  
	  return post_id;
	  
}
	
/*
 * The following code which obtaines machine ID from machine's MAC address was
 * inspired from https://stackoverflow.com/a/16859693.
 */
u_int16_t HashMacAddressPid(const std::string &mac)
{
  u_int16_t hash = 0;
  std::string mac_pid = mac + std::to_string(getpid());
  for ( unsigned int i = 0; i < mac_pid.size(); i++ ) {
    hash += ( mac[i] << (( i & 1 ) * 8 ));
  }
  return hash;
}

int GetMachineId (std::string *mac_hash) {
  std::string mac;
  int sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_IP );
  if ( sock < 0 ) {
    cout << "Unable to obtain MAC address" <<endl;
    return -1;
  }

  struct ifconf conf{};
  char ifconfbuf[ 128 * sizeof(struct ifreq)  ];
  memset( ifconfbuf, 0, sizeof( ifconfbuf ));
  conf.ifc_buf = ifconfbuf;
  conf.ifc_len = sizeof( ifconfbuf );
  if ( ioctl( sock, SIOCGIFCONF, &conf ))
  {
    cout << "Unable to obtain MAC address";
    return -1;
  }

  struct ifreq* ifr;
  for (
      ifr = conf.ifc_req;
      reinterpret_cast<char *>(ifr) <
          reinterpret_cast<char *>(conf.ifc_req) + conf.ifc_len;
      ifr++) {
    if ( ifr->ifr_addr.sa_data == (ifr+1)->ifr_addr.sa_data ) {
      continue;  // duplicate, skip it
    }

    if ( ioctl( sock, SIOCGIFFLAGS, ifr )) {
      continue;  // failed to get flags, skip it
    }
    if ( ioctl( sock, SIOCGIFHWADDR, ifr ) == 0 ) {
      mac = std::string(ifr->ifr_addr.sa_data);
      if (!mac.empty()) {
        break;
      }
    }
  }
  close(sock);

  std::stringstream stream;
  stream << std::hex << HashMacAddressPid(mac);
  *mac_hash = stream.str();

  if (mac_hash->size() > 3) {
    mac_hash->erase(0, mac_hash->size() - 3);
  } else if (mac_hash->size() < 3) {
    *mac_hash = std::string(3 - mac_hash->size(), '0') + *mac_hash;
  }
  return 0;
}
//------------------------------------------------------------------------------
// Main
//------------------------------------------------------------------------------


#include <iostream>
#include <vector>
#include <cstring>



constexpr int MAX_KEY_LEN = 32;
constexpr int N = 4;
constexpr int MAX_RESULTS = 8;

int main() {
    NotificationMap notif_map{};
    notif_map.next_slot = 0;

    // ------------------------------------------------------------------
    // Step 1: Build posts and mentions (each post has multiple usernames)
    // ------------------------------------------------------------------
    int64_t postIDs[N] = {1001, 1002, 1003, 1004};
    int num_per_post[N] = {2, 3, 1, 4};
    int start_idx[N];

    // Compute start_idx dynamically
    start_idx[0] = 0;
    for (int i = 1; i < N; i++)
        start_idx[i] = start_idx[i - 1] + num_per_post[i - 1];

    int total_usernames = start_idx[N - 1] + num_per_post[N - 1];
    std::vector<uint8_t> usernames_flat(total_usernames * MAX_KEY_LEN);

    const char* groups[][4] = {
        {"A", "B"},
        {"A", "B", "C"},
        {"A"},
        {"A", "B", "C", "D"}
    };

    // Fill flat buffer
    int idx = 0;
    for (int i = 0; i < N; i++) {
        for (int j = 0; j < num_per_post[i]; j++) {
            strncpy((char*)&usernames_flat[idx * MAX_KEY_LEN],
                    groups[i][j], MAX_KEY_LEN);
            idx++;
        }
    }

    // ------------------------------------------------------------------
    // Step 2: Run insertion kernel
    // ------------------------------------------------------------------
    std::cout << "\n=== Inserting Mentions ===\n";
    
    // Timing arrays for insertion
    std::vector<int64_t> lane_start_insert(N);
    std::vector<int64_t> lane_end_insert(N);
    int64_t global_start_insert = 0;
    
    auto start_insert = std::chrono::high_resolution_clock::now();
    ispc::userMention_flat_batch(notif_map,
                                 usernames_flat.data(),
                                 start_idx,
                                 num_per_post,
                                 postIDs,
                                 N,
                                 lane_start_insert.data(),
                                 lane_end_insert.data(),
                                 global_start_insert);
    auto end_insert = std::chrono::high_resolution_clock::now();
    
    auto duration_insert = std::chrono::duration_cast<std::chrono::microseconds>(end_insert - start_insert);
    std::cout << "Insertion batch completed in " << duration_insert.count() << " µs\n";

    // Print inserted map
    std::cout << "\n=== NotificationMap contents ===\n";
    for (int i = 0; i < notif_map.next_slot; i++) {
        std::cout << "[" << i << "] key=" << notif_map.keys[i]
                  << "  postID=" << notif_map.values[i] << "\n";
    }

    // ------------------------------------------------------------------
    // Step 3: Prepare lookup queries
    // ------------------------------------------------------------------
    const char* queries[] = {"A", "B", "C", "Z"};
    constexpr int Q = 4;

    uint8_t query_flat[Q * MAX_KEY_LEN] = {};
    for (int i = 0; i < Q; i++)
        strncpy((char*)&query_flat[i * MAX_KEY_LEN], queries[i], MAX_KEY_LEN);

    int64_t results[Q * MAX_RESULTS] = {};
    int counts[Q] = {};

    // ------------------------------------------------------------------
    // Step 4: Run lookup kernel
    // ------------------------------------------------------------------
    std::cout << "\n=== Running Parallel Lookups ===\n";
    
    // Timing arrays for lookup
    std::vector<int64_t> lane_start_lookup(Q);
    std::vector<int64_t> lane_end_lookup(Q);
    int64_t global_start_lookup = 0;
    
    auto start_lookup = std::chrono::high_resolution_clock::now();
    ispc::getMentionNotifications_batch(notif_map,
                                        query_flat,
                                        Q,
                                        results,
                                        MAX_RESULTS,
                                        counts,
                                        lane_start_lookup.data(),
                                        lane_end_lookup.data(),
                                        global_start_lookup);
    auto end_lookup = std::chrono::high_resolution_clock::now();
    
    auto duration_lookup = std::chrono::duration_cast<std::chrono::microseconds>(end_lookup - start_lookup);
    std::cout << "Lookup batch completed in " << duration_lookup.count() << " µs\n";

    // ------------------------------------------------------------------
    // Step 5: Print lookup results
    // ------------------------------------------------------------------
    std::cout << "\n=== Lookup Results ===\n";
    for (int i = 0; i < Q; i++) {
        std::cout << "Username " << queries[i]
                  << " → " << counts[i] << " posts\n";
        for (int j = 0; j < counts[i]; j++) {
            std::cout << "   postID = "
                      << results[i * MAX_RESULTS + j] << "\n";
        }
        std::cout << "-----------------------------------\n";
    }

    // ------------------------------------------------------------------
    // TIMING ANALYSIS - Insertion
    // ------------------------------------------------------------------
    std::cout << "\n╔══════════════════════════════════════════════════════════════════╗\n";
    std::cout << "║       TIMING ANALYSIS - userMention_flat_batch (N=" << N << ")           ║\n";
    std::cout << "╚══════════════════════════════════════════════════════════════════╝\n\n";
    
    std::cout << "Per-Lane Timing (cycles):\n";
    std::cout << "Lane | PostID | #Users | Queue Delay | Exec Time  | Total Latency\n";
    std::cout << "-----+--------+--------+-------------+------------+--------------\n";
    
    for (int i = 0; i < N; i++) {
        int64_t queue_delay = lane_start_insert[i] - global_start_insert;
        int64_t exec_time = lane_end_insert[i] - lane_start_insert[i];
        int64_t total_latency = lane_end_insert[i] - global_start_insert;
        
        std::cout << std::setw(4) << i << " | "
                  << std::setw(6) << postIDs[i] << " | "
                  << std::setw(6) << num_per_post[i] << " | "
                  << std::setw(11) << queue_delay << " | "
                  << std::setw(10) << exec_time << " | "
                  << std::setw(12) << total_latency << "\n";
    }
    
    // ------------------------------------------------------------------
    // TIMING ANALYSIS - Lookup
    // ------------------------------------------------------------------
    std::cout << "\n╔══════════════════════════════════════════════════════════════════╗\n";
    std::cout << "║       TIMING ANALYSIS - getMentionNotifications_batch (N=" << Q << ")    ║\n";
    std::cout << "╚══════════════════════════════════════════════════════════════════╝\n\n";
    
    std::cout << "Per-Lane Timing (cycles):\n";
    std::cout << "Lane | Username | #Found | Queue Delay | Exec Time  | Total Latency\n";
    std::cout << "-----+----------+--------+-------------+------------+--------------\n";
    
    for (int i = 0; i < Q; i++) {
        int64_t queue_delay = lane_start_lookup[i] - global_start_lookup;
        int64_t exec_time = lane_end_lookup[i] - lane_start_lookup[i];
        int64_t total_latency = lane_end_lookup[i] - global_start_lookup;
        
        std::cout << std::setw(4) << i << " | "
                  << std::setw(8) << queries[i] << " | "
                  << std::setw(6) << counts[i] << " | "
                  << std::setw(11) << queue_delay << " | "
                  << std::setw(10) << exec_time << " | "
                  << std::setw(12) << total_latency << "\n";
    }
    
    // Analyze workload impact
    std::cout << "\n📊 Workload Analysis:\n";
    std::cout << "   Insertion: Lanes process different #users per post\n";
    for (int i = 0; i < N; i++) {
        int64_t exec_time = lane_end_insert[i] - lane_start_insert[i];
        std::cout << "      Lane " << i << " (" << num_per_post[i] 
                  << " users): " << exec_time << " cycles\n";
    }
    
    std::cout << "\n   Lookup: Different result set sizes\n";
    for (int i = 0; i < Q; i++) {
        int64_t exec_time = lane_end_lookup[i] - lane_start_lookup[i];
        std::cout << "      Lane " << i << " ('" << queries[i] 
                  << "', " << counts[i] << " posts): " << exec_time << " cycles\n";
    }

    // ------------------------------------------------------------------
    // DUMP TIMING DATA TO CSV
    // ------------------------------------------------------------------
    FILE* csv_file = fopen("timing_stats.csv", "w");
    if (csv_file) {
        // Write header
        fprintf(csv_file, "Operation,Lane,QueueingDelay,ExecutionTime,TotalLatency\n");
        
        // Write insertion timing data
        for (int i = 0; i < N; i++) {
            int64_t queue_delay = lane_start_insert[i] - global_start_insert;
            int64_t exec_time = lane_end_insert[i] - lane_start_insert[i];
            int64_t total_latency = lane_end_insert[i] - global_start_insert;
            
            fprintf(csv_file, "Insertion,%d,%ld,%ld,%ld\n", i, queue_delay, exec_time, total_latency);
        }
        
        // Write lookup timing data
        for (int i = 0; i < Q; i++) {
            int64_t queue_delay = lane_start_lookup[i] - global_start_lookup;
            int64_t exec_time = lane_end_lookup[i] - lane_start_lookup[i];
            int64_t total_latency = lane_end_lookup[i] - global_start_lookup;
            
            fprintf(csv_file, "Lookup,%d,%ld,%ld,%ld\n", i, queue_delay, exec_time, total_latency);
        }
        
        fclose(csv_file);
        std::cout << "\n✅ Timing data exported to 'timing_stats.csv'\n";
    } else {
        std::cerr << "\n❌ Failed to create CSV file\n";
    }
    
    // ------------------------------------------------------------------
    // DUMP THROUGHPUT STATS TO CSV
    // ------------------------------------------------------------------
    FILE* throughput_file = fopen("throughput_stats.csv", "w");
    if (throughput_file) {
        // Write header
        fprintf(throughput_file, "Operation,Metric,Value,Unit\n");
        
        // Insertion metrics
        double throughput_insert = (N * 1000000.0 / duration_insert.count());
        fprintf(throughput_file, "Insertion,BatchSize,%d,posts\n", N);
        fprintf(throughput_file, "Insertion,TotalTime,%ld,microseconds\n", duration_insert.count());
        fprintf(throughput_file, "Insertion,Throughput,%.2f,posts/sec\n", throughput_insert);
        fprintf(throughput_file, "Insertion,AvgLatencyPerPost,%.2f,nanoseconds\n", (duration_insert.count() * 1000.0 / N));
        
        // Lookup metrics
        double throughput_lookup = (Q * 1000000.0 / duration_lookup.count());
        fprintf(throughput_file, "Lookup,BatchSize,%d,queries\n", Q);
        fprintf(throughput_file, "Lookup,TotalTime,%ld,microseconds\n", duration_lookup.count());
        fprintf(throughput_file, "Lookup,Throughput,%.2f,queries/sec\n", throughput_lookup);
        fprintf(throughput_file, "Lookup,AvgLatencyPerQuery,%.2f,nanoseconds\n", (duration_lookup.count() * 1000.0 / Q));
        
        // Per-lane statistics
        fprintf(throughput_file, "\nOperation,Lane,AvgQueueDelay,AvgExecTime,AvgTotalLatency,Unit\n");
        
        for (int i = 0; i < N; i++) {
            int64_t queue_delay = lane_start_insert[i] - global_start_insert;
            int64_t exec_time = lane_end_insert[i] - lane_start_insert[i];
            int64_t latency = lane_end_insert[i] - global_start_insert;
            fprintf(throughput_file, "Insertion,%d,%ld,%ld,%ld,cycles\n", i, queue_delay, exec_time, latency);
        }
        
        for (int i = 0; i < Q; i++) {
            int64_t queue_delay = lane_start_lookup[i] - global_start_lookup;
            int64_t exec_time = lane_end_lookup[i] - lane_start_lookup[i];
            int64_t latency = lane_end_lookup[i] - global_start_lookup;
            fprintf(throughput_file, "Lookup,%d,%ld,%ld,%ld,cycles\n", i, queue_delay, exec_time, latency);
        }
        
        // Workload analysis
        fprintf(throughput_file, "\nOperation,Lane,Workload,ExecTime,Unit\n");
        for (int i = 0; i < N; i++) {
            int64_t exec_time = lane_end_insert[i] - lane_start_insert[i];
            fprintf(throughput_file, "Insertion,%d,%d,%ld,cycles\n", i, num_per_post[i], exec_time);
        }
        
        for (int i = 0; i < Q; i++) {
            int64_t exec_time = lane_end_lookup[i] - lane_start_lookup[i];
            fprintf(throughput_file, "Lookup,%d,%d,%ld,cycles\n", i, counts[i], exec_time);
        }
        
        fclose(throughput_file);
        std::cout << "✅ Throughput stats exported to 'throughput_stats.csv'\n";
    } else {
        std::cerr << "❌ Failed to create throughput CSV file\n";
    }

    std::cout << "\nDone.\n";
    return 0;
}
