/*
  Copyright (c) 2010-2025, Intel Corporation
  SPDX-License-Identifier: BSD-3-Clause
*/

#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <algorithm>
#include <string>
#include <vector>
#include <chrono>
#include <mutex>
#include <sstream>
#include <iomanip>
#include <atomic>
#include <cmath>
#include <arpa/inet.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <signal.h>
#include <unistd.h>
#include <string.h>
using namespace std;

// Include energy measurement header
#include "../energy_measurement.h"

// Include ISPC header (generated by the ISPC compiler)
#include "simple_ispc.h"
using namespace ispc;

// Include multithreaded version
#include "simple_mt.h"

#include <sys/socket.h>
#include <signal.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
using namespace std;


 
 
 static int64_t current_timestamp = -1;
//static int counter = 0;
std::string machine_id;
std::mutex _thread_lock;
	  
static	  std::atomic<int> counter{0};


#define CUSTOM_EPOCH 1514764800000

using std::chrono::milliseconds;
using std::chrono::duration_cast;
using std::chrono::system_clock;

static int GetCounter(int64_t timestamp) {
  if (current_timestamp > timestamp) {
    cout << "Timestamps are not incremental."<<endl;
    exit(EXIT_FAILURE);
  }
  if (current_timestamp == timestamp) {
    return counter++;
  } else {
	  _thread_lock.lock();
    current_timestamp = timestamp;
    counter = 0;
	_thread_lock.unlock();
    return counter++;
  }
}

int64_t UploadUniqueId(
	int64_t req_id
	) 
	{

  int64_t timestamp = duration_cast<milliseconds>(
      system_clock::now().time_since_epoch()).count() - CUSTOM_EPOCH;
  //
  int idx = GetCounter(timestamp);

  std::stringstream sstream;
  sstream << std::hex << timestamp;
  std::string timestamp_hex(sstream.str());

  if (timestamp_hex.size() > 10) {
    timestamp_hex.erase(0, timestamp_hex.size() - 10);
  } else if (timestamp_hex.size() < 10) {
    timestamp_hex = std::string(10 - timestamp_hex.size(), '0') + timestamp_hex;
  }

  // Empty the sstream buffer.
  sstream.clear();
  sstream.str(std::string());

  sstream << std::hex << idx;
  std::string counter_hex(sstream.str());

  if (counter_hex.size() > 3) {
    counter_hex.erase(0, counter_hex.size() - 3);
  } else if (counter_hex.size() < 3) {
    counter_hex = std::string(3 - counter_hex.size(), '0') + counter_hex;
  }
  std::string post_id_str = machine_id + timestamp_hex + counter_hex;
  int64_t post_id = stoul(post_id_str, nullptr, 16) & 0x7FFFFFFFFFFFFFFF;
  //cout << "The post_id of the request "
  //    << req_id << " is " << post_id<<endl;
	  
	  return post_id;
	  
}
	
/*
 * The following code which obtaines machine ID from machine's MAC address was
 * inspired from https://stackoverflow.com/a/16859693.
 */
u_int16_t HashMacAddressPid(const std::string &mac)
{
  u_int16_t hash = 0;
  std::string mac_pid = mac + std::to_string(getpid());
  for ( unsigned int i = 0; i < mac_pid.size(); i++ ) {
    hash += ( mac[i] << (( i & 1 ) * 8 ));
  }
  return hash;
}

int GetMachineId (std::string *mac_hash) {
  std::string mac;
  int sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_IP );
  if ( sock < 0 ) {
    cout << "Unable to obtain MAC address" <<endl;
    return -1;
  }

  struct ifconf conf{};
  char ifconfbuf[ 128 * sizeof(struct ifreq)  ];
  memset( ifconfbuf, 0, sizeof( ifconfbuf ));
  conf.ifc_buf = ifconfbuf;
  conf.ifc_len = sizeof( ifconfbuf );
  if ( ioctl( sock, SIOCGIFCONF, &conf ))
  {
    cout << "Unable to obtain MAC address";
    return -1;
  }

  struct ifreq* ifr;
  for (
      ifr = conf.ifc_req;
      reinterpret_cast<char *>(ifr) <
          reinterpret_cast<char *>(conf.ifc_req) + conf.ifc_len;
      ifr++) {
    if ( ifr->ifr_addr.sa_data == (ifr+1)->ifr_addr.sa_data ) {
      continue;  // duplicate, skip it
    }

    if ( ioctl( sock, SIOCGIFFLAGS, ifr )) {
      continue;  // failed to get flags, skip it
    }
    if ( ioctl( sock, SIOCGIFHWADDR, ifr ) == 0 ) {
      mac = std::string(ifr->ifr_addr.sa_data);
      if (!mac.empty()) {
        break;
      }
    }
  }
  close(sock);

  std::stringstream stream;
  stream << std::hex << HashMacAddressPid(mac);
  *mac_hash = stream.str();

  if (mac_hash->size() > 3) {
    mac_hash->erase(0, mac_hash->size() - 3);
  } else if (mac_hash->size() < 3) {
    *mac_hash = std::string(3 - mac_hash->size(), '0') + *mac_hash;
  }
  return 0;
}
//------------------------------------------------------------------------------
// Main
//------------------------------------------------------------------------------


#include <iostream>
#include <vector>
#include <cstring>

// Use defines from simple_mt.h (MAX_KEY_LEN, MAX_ENTRIES)
constexpr int MAX_RESULTS = 8;

int main(int argc, char* argv[]) {
    // Parse command-line arguments
    bool use_ispc = true;
    int num_threads = 0;
    int batch_size = 4;     // Default batch size (number of requests)
    std::string test_type = "insert";  // Default test type: "insert" or "lookup"
    std::string mt_mode = "pool";      // Default MT mode: "pool" or "spawn"
    int warmup_iters = 5;   // Warm-up iterations
    int bench_iters = 50;   // Benchmark iterations
    
    if (argc > 1) {
        std::string mode_str = argv[1];
        if (mode_str == "mt" || mode_str == "multithreaded") {
            use_ispc = false;
            if (argc > 2) {
                num_threads = std::atoi(argv[2]);
            }
            if (argc > 3) {
                test_type = argv[3];
            }
            if (argc > 4) {
                mt_mode = argv[4];
            }
            if (argc > 5) {
                batch_size = std::atoi(argv[5]);
            }
            if (argc > 6) {
                bench_iters = std::atoi(argv[6]);
            }
        } else if (mode_str == "ispc") {
            use_ispc = true;
            if (argc > 2) {
                test_type = argv[2];
            }
            if (argc > 3) {
                batch_size = std::atoi(argv[3]);
            }
            if (argc > 4) {
                bench_iters = std::atoi(argv[4]);
            }
        } else {
            std::cerr << "Usage: " << argv[0] << " [mode] [test_type] [batch_size] [iterations]\n";
            std::cerr << "       " << argv[0] << " mt [num_threads] [test_type] [mt_mode] [batch_size] [iterations]\n\n";
            std::cerr << "Arguments:\n";
            std::cerr << "  mode:          'ispc' or 'mt' (multithreaded)\n";
            std::cerr << "  num_threads:   Number of threads (only for mt mode, default=auto)\n";
            std::cerr << "  test_type:     'insert' or 'lookup' (default='insert')\n";
            std::cerr << "  mt_mode:       'pool' or 'spawn' (only for mt mode, default='pool')\n";
            std::cerr << "  batch_size:    Number of requests (default=4)\n";
            std::cerr << "  iterations:    Benchmark iterations (default=50)\n";
            std::cerr << "\nExamples:\n";
            std::cerr << "  " << argv[0] << " ispc insert 4 100           # ISPC, insert test, 4 requests, 100 iterations\n";
            std::cerr << "  " << argv[0] << " ispc lookup 8 100           # ISPC, lookup test, 8 queries, 100 iterations\n";
            std::cerr << "  " << argv[0] << " mt 8 insert pool 4 100      # MT pool, 8 threads, insert, 4 requests, 100 iterations\n";
            std::cerr << "  " << argv[0] << " mt 8 lookup spawn 8 100     # MT spawn, 8 threads, lookup, 8 queries, 100 iterations\n";
            return 1;
        }
    }
    
    // Validate test_type
    if (test_type != "insert" && test_type != "lookup") {
        std::cerr << "Error: test_type must be 'insert' or 'lookup'\n";
        return 1;
    }
    
    // Validate mt_mode
    if (mt_mode != "pool" && mt_mode != "spawn") {
        std::cerr << "Error: mt_mode must be 'pool' or 'spawn'\n";
        return 1;
    }
    
    std::string mode_name = use_ispc ? "ISPC SIMD" : ("Multithreaded (" + mt_mode + ")");
    std::cout << "\n╔══════════════════════════════════════════════════════════════════╗\n";
    std::cout << "║  USER TAG SERVICE                                                ║\n";
    std::cout << "╠══════════════════════════════════════════════════════════════════╣\n";
    std::cout << "║  Mode: " << mode_name << std::string(58 - mode_name.length(), ' ') << "║\n";
    std::cout << "║  Test Type: " << test_type << std::string(53 - test_type.length(), ' ') << "║\n";
    if (!use_ispc && num_threads > 0) {
        std::cout << "║  Threads: " << num_threads << std::string(55 - std::to_string(num_threads).length(), ' ') << "║\n";
    } else if (!use_ispc) {
        std::cout << "║  Threads: Auto-detect                                          ║\n";
    }
    std::cout << "║  Warmup Iterations: " << warmup_iters << std::string(45 - std::to_string(warmup_iters).length(), ' ') << "║\n";
    std::cout << "║  Benchmark Iterations: " << bench_iters << std::string(42 - std::to_string(bench_iters).length(), ' ') << "║\n";
    std::cout << "╚══════════════════════════════════════════════════════════════════╝\n\n";
    
    // Initialize thread pool for multithreaded mode
    ThreadPool::Mode pool_mode = (mt_mode == "spawn") ? ThreadPool::SPAWN_MODE : ThreadPool::POOL_MODE;
    if (!use_ispc) {
        std::cout << "🔧 Initializing thread pool with " << (num_threads > 0 ? num_threads : std::thread::hardware_concurrency()) << " threads (" << mt_mode << " mode)...\n";
        mt::InitThreadPool(num_threads, pool_mode);
        std::cout << "✅ Thread pool ready\n\n";
    }
    
    // Initialize energy monitoring
    EnergyMonitor energy_monitor;
    std::string energy_mode = use_ispc ? "ispc" : mt_mode;
    EnergyStats insert_energy_stats("insert_" + energy_mode);
    EnergyStats lookup_energy_stats("lookup_" + energy_mode);
    
    // Initialize notification map (ISPC or MT version)
    NotificationMap* ispc_map = nullptr;
    mt::NotificationMap* mt_map = nullptr;
    
    if (use_ispc) {
        ispc_map = new NotificationMap{};
        ispc_map->next_slot = 0;
        // Initialize hash table with -1 (empty)
        for (int i = 0; i < 8192; i++) {
            ispc_map->hashTable[i] = -1;
        }
        // Initialize next indices
        for (int i = 0; i < 4096; i++) {
            ispc_map->nextIndices[i] = -1;
        }
    } else {
        mt_map = new mt::NotificationMap{};
        // Initialize hash table with -1 (empty)
        for (int i = 0; i < 2048; i++) {
            mt_map->hashTable[i][0].store(-1, std::memory_order_relaxed);
            mt_map->hashTable[i][1].store(-1, std::memory_order_relaxed);
        }
        // Initialize next indices
        for (int i = 0; i < 1024; i++) {
            mt_map->nextIndices[i].store(-1, std::memory_order_relaxed);
        }
    }

    // ------------------------------------------------------------------
    // Step 1: Prepare data based on test type
    // ------------------------------------------------------------------
    
    // Common timing arrays
    std::vector<int64_t> lane_start_times;
    std::vector<int64_t> lane_end_times;
    int64_t global_start_time = 0;
    
    // Accumulators for averaging timing across iterations
    std::vector<double> avg_queue_delay;
    std::vector<double> avg_exec_time;
    std::vector<double> avg_total_latency;
    
    // Data for INSERT test
    std::vector<int64_t> postIDs;
    std::vector<int> num_per_post;
    std::vector<int> start_idx;
    std::vector<uint8_t> usernames_flat;
    int total_usernames = 0;
    
    // Data for LOOKUP test
    int lookup_queries = batch_size;
    std::vector<std::string> query_strings;
    std::vector<uint8_t> query_flat;
    std::vector<int64_t> results;
    std::vector<int> counts;
    
    if (test_type == "insert") {
        // Prepare INSERT data
        lane_start_times.resize(batch_size);
        lane_end_times.resize(batch_size);
        avg_queue_delay.resize(batch_size, 0.0);
        avg_exec_time.resize(batch_size, 0.0);
        avg_total_latency.resize(batch_size, 0.0);
        postIDs.resize(batch_size);
        num_per_post.resize(batch_size);
        start_idx.resize(batch_size);
        
        // Seed random number generator
        std::srand(42);  // Fixed seed for reproducibility
        
        // Generate post IDs and users per post (exactly 4 users per post)
        for (int i = 0; i < batch_size; i++) {
            postIDs[i] = 1001 + i;
            num_per_post[i] = 4;  // All posts mention exactly 4 users
        }
        
        // Compute start_idx dynamically
        start_idx[0] = 0;
        for (int i = 1; i < batch_size; i++)
            start_idx[i] = start_idx[i - 1] + num_per_post[i - 1];

        total_usernames = start_idx[batch_size - 1] + num_per_post[batch_size - 1];
        usernames_flat.resize(total_usernames * MAX_KEY_LEN);

        // Generate random usernames (user_0 to user_999)
        int idx = 0;
        for (int i = 0; i < batch_size; i++) {
            for (int j = 0; j < num_per_post[i]; j++) {
                // Generate random username: user_<number>
                int user_id = std::rand() % 1000;  // 0-999
                std::string username = "user_" + std::to_string(user_id);
                strncpy((char*)&usernames_flat[idx * MAX_KEY_LEN],
                        username.c_str(), MAX_KEY_LEN - 1);
                usernames_flat[idx * MAX_KEY_LEN + MAX_KEY_LEN - 1] = '\0';  // Ensure null termination
                idx++;
            }
        }
    } else {  // lookup
        // Prepare LOOKUP data
        lane_start_times.resize(lookup_queries);
        lane_end_times.resize(lookup_queries);
        avg_queue_delay.resize(lookup_queries, 0.0);
        avg_exec_time.resize(lookup_queries, 0.0);
        avg_total_latency.resize(lookup_queries, 0.0);
        query_flat.resize(lookup_queries * MAX_KEY_LEN);
        results.resize(lookup_queries * MAX_RESULTS);
        counts.resize(lookup_queries);
        
        // First, pre-populate the map with INSERT data
        std::cout << "🔧 Pre-populating map for lookup test...\n";
        
        // Seed random number generator
        std::srand(42);  // Same seed for consistency
        
        // Use 100 posts for pre-population to have meaningful data
        int seed_posts = 100;
        postIDs.resize(seed_posts);
        num_per_post.resize(seed_posts);
        start_idx.resize(seed_posts);
        
        for (int i = 0; i < seed_posts; i++) {
            postIDs[i] = 1001 + i;
            num_per_post[i] = 4;  // All posts mention exactly 4 users
        }
        
        start_idx[0] = 0;
        for (int i = 1; i < seed_posts; i++)
            start_idx[i] = start_idx[i - 1] + num_per_post[i - 1];
        total_usernames = start_idx[seed_posts - 1] + num_per_post[seed_posts - 1];
        usernames_flat.resize(total_usernames * MAX_KEY_LEN);
        
        // Generate random usernames for pre-population
        int idx = 0;
        for (int i = 0; i < seed_posts; i++) {
            for (int j = 0; j < num_per_post[i]; j++) {
                int user_id = std::rand() % 1000;
                std::string username = "user_" + std::to_string(user_id);
                strncpy((char*)&usernames_flat[idx * MAX_KEY_LEN],
                        username.c_str(), MAX_KEY_LEN - 1);
                usernames_flat[idx * MAX_KEY_LEN + MAX_KEY_LEN - 1] = '\0';
                idx++;
            }
        }
        
        std::vector<int64_t> temp_start(seed_posts);
        std::vector<int64_t> temp_end(seed_posts);
        int64_t temp_global = 0;
        
        if (use_ispc) {
            ispc::userMention_flat_batch(*ispc_map,
                                         usernames_flat.data(),
                                         start_idx.data(),
                                         num_per_post.data(),
                                         postIDs.data(),
                                         seed_posts,
                                         temp_start.data(),
                                         temp_end.data(),
                                         temp_global);
        } else {
            mt::userMention_flat_batch(*mt_map,
                                       usernames_flat.data(),
                                       start_idx.data(),
                                       num_per_post.data(),
                                       postIDs.data(),
                                       seed_posts,
                                       temp_start.data(),
                                       temp_end.data(),
                                       temp_global,
                                       num_threads);
        }
        
        std::cout << "✅ Map pre-populated with " << seed_posts << " posts and " << total_usernames << " username mentions\n\n";
        
        // Prepare lookup queries - mix of existing and non-existing users
        query_strings.resize(lookup_queries);
        for (int i = 0; i < lookup_queries; i++) {
            // 75% chance to query an existing user, 25% chance for non-existing
            if (std::rand() % 4 < 3) {
                // Query an existing user (from 0-999 range used in pre-population)
                int user_id = std::rand() % 1000;
                query_strings[i] = "user_" + std::to_string(user_id);
            } else {
                // Query a non-existing user
                int user_id = 1000 + (std::rand() % 100);  // user_1000 to user_1099 (not in pre-population)
                query_strings[i] = "user_" + std::to_string(user_id);
            }
            strncpy((char*)&query_flat[i * MAX_KEY_LEN], query_strings[i].c_str(), MAX_KEY_LEN - 1);
            query_flat[i * MAX_KEY_LEN + MAX_KEY_LEN - 1] = '\0';
        }
    }

    // ------------------------------------------------------------------
    // Step 2: WARM-UP PHASE
    // ------------------------------------------------------------------
    std::cout << "🔥 Warming up: " << warmup_iters << " iterations...\n";
    for (int w = 0; w < warmup_iters; w++) {
        // Reset map before each warmup iteration (only for insert tests)
        if (test_type == "insert") {
            if (use_ispc) {
                ispc_map->next_slot = 0;
                // Reset hash table
                for (int i = 0; i < 8192; i++) {
                    ispc_map->hashTable[i] = -1;
                }
                for (int i = 0; i < 4096; i++) {
                    ispc_map->nextIndices[i] = -1;
                }
            } else {
                mt_map->next_slot.store(0);
            }
        }
        
        if (test_type == "insert") {
            if (use_ispc) {
                ispc::userMention_flat_batch(*ispc_map,
                                             usernames_flat.data(),
                                             start_idx.data(),
                                             num_per_post.data(),
                                             postIDs.data(),
                                             batch_size,
                                             lane_start_times.data(),
                                             lane_end_times.data(),
                                             global_start_time);
            } else {
                mt::userMention_flat_batch(*mt_map,
                                           usernames_flat.data(),
                                           start_idx.data(),
                                           num_per_post.data(),
                                           postIDs.data(),
                                           batch_size,
                                           lane_start_times.data(),
                                           lane_end_times.data(),
                                           global_start_time,
                                           num_threads);
            }
        } else {  // lookup
            if (use_ispc) {
                ispc::getMentionNotifications_batch(*ispc_map,
                                                    query_flat.data(),
                                                    lookup_queries,
                                                    results.data(),
                                                    MAX_RESULTS,
                                                    counts.data(),
                                                    lane_start_times.data(),
                                                    lane_end_times.data(),
                                                    global_start_time);
            } else {
                mt::getMentionNotifications_batch(*mt_map,
                                                  query_flat.data(),
                                                  lookup_queries,
                                                  results.data(),
                                                  MAX_RESULTS,
                                                  counts.data(),
                                                  lane_start_times.data(),
                                                  lane_end_times.data(),
                                                  global_start_time,
                                                  num_threads);
            }
        }
    }
    std::cout << "✅ Warm-up complete\n\n";

    // ------------------------------------------------------------------
    // Step 3: BENCHMARK PHASE
    // ------------------------------------------------------------------
    std::cout << "📊 Benchmarking: " << bench_iters << " iterations...\n";
    std::vector<int64_t> time_measurements_us;
    
    for (int iter = 0; iter < bench_iters; iter++) {
        // Reset map before each benchmark iteration (only for insert tests to prevent buffer overflow)
        if (test_type == "insert") {
            if (use_ispc) {
                ispc_map->next_slot = 0;
                // Reset hash table
                for (int i = 0; i < 8192; i++) {
                    ispc_map->hashTable[i] = -1;
                }
                for (int i = 0; i < 4096; i++) {
                    ispc_map->nextIndices[i] = -1;
                }
            } else {
                mt_map->next_slot.store(0);
            }
        }
        
        // Start energy measurement
        EnergyMeasurement energy_start = energy_monitor.start();
        
        auto start_bench = std::chrono::high_resolution_clock::now();
        
        if (test_type == "insert") {
            if (use_ispc) {
                ispc::userMention_flat_batch(*ispc_map,
                                             usernames_flat.data(),
                                             start_idx.data(),
                                             num_per_post.data(),
                                             postIDs.data(),
                                             batch_size,
                                             lane_start_times.data(),
                                             lane_end_times.data(),
                                             global_start_time);
            } else {
                mt::userMention_flat_batch(*mt_map,
                                           usernames_flat.data(),
                                           start_idx.data(),
                                           num_per_post.data(),
                                           postIDs.data(),
                                           batch_size,
                                           lane_start_times.data(),
                                           lane_end_times.data(),
                                           global_start_time,
                                           num_threads);
            }
        } else {  // lookup
            if (use_ispc) {
                ispc::getMentionNotifications_batch(*ispc_map,
                                                    query_flat.data(),
                                                    lookup_queries,
                                                    results.data(),
                                                    MAX_RESULTS,
                                                    counts.data(),
                                                    lane_start_times.data(),
                                                    lane_end_times.data(),
                                                    global_start_time);
            } else {
                mt::getMentionNotifications_batch(*mt_map,
                                                  query_flat.data(),
                                                  lookup_queries,
                                                  results.data(),
                                                  MAX_RESULTS,
                                                  counts.data(),
                                                  lane_start_times.data(),
                                                  lane_end_times.data(),
                                                  global_start_time,
                                                  num_threads);
            }
        }
        
        auto end_bench = std::chrono::high_resolution_clock::now();
        auto duration = std::chrono::duration_cast<std::chrono::microseconds>(end_bench - start_bench);
        time_measurements_us.push_back(duration.count());
        
        // End energy measurement and add to appropriate stats
        EnergyMeasurement energy_delta = energy_monitor.end(energy_start);
        if (test_type == "insert") {
            EnergyMonitor::add_measurement(insert_energy_stats, energy_delta);
        } else {
            EnergyMonitor::add_measurement(lookup_energy_stats, energy_delta);
        }
        
        // Accumulate relative timing metrics for this iteration
        int current_size = (test_type == "insert") ? batch_size : lookup_queries;
        for (int i = 0; i < current_size; i++) {
            int64_t queue_delay = lane_start_times[i] - global_start_time;
            int64_t exec_time = lane_end_times[i] - lane_start_times[i];
            int64_t total_latency = lane_end_times[i] - global_start_time;
            
            avg_queue_delay[i] += queue_delay;
            avg_exec_time[i] += exec_time;
            avg_total_latency[i] += total_latency;
        }
        
        // Progress indicator
        if (bench_iters >= 20 && (iter + 1) % (bench_iters / 10) == 0) {
            std::cout << "  Progress: " << (iter + 1) << "/" << bench_iters << "\n";
        }
    }
    
    // Calculate averages
    int current_size = (test_type == "insert") ? batch_size : lookup_queries;
    for (int i = 0; i < current_size; i++) {
        avg_queue_delay[i] /= bench_iters;
        avg_exec_time[i] /= bench_iters;
        avg_total_latency[i] /= bench_iters;
    }
    
    std::cout << "✅ Benchmarking complete\n\n";
    
    // Calculate statistics
    std::sort(time_measurements_us.begin(), time_measurements_us.end());
    int64_t min_time = time_measurements_us.front();
    int64_t max_time = time_measurements_us.back();
    int64_t median_time = time_measurements_us[bench_iters / 2];
    int64_t mean_time = 0;
    for (auto t : time_measurements_us) mean_time += t;
    mean_time /= bench_iters;
    
    double stddev = 0;
    for (auto t : time_measurements_us) {
        stddev += (t - mean_time) * (t - mean_time);
    }
    stddev = std::sqrt(stddev / bench_iters);
    double cv = (stddev / mean_time) * 100.0;
    
    int display_batch_size = (test_type == "insert") ? batch_size : lookup_queries;
    std::string kernel_name = (test_type == "insert") ? "userMention_flat_batch" : "getMentionNotifications_batch";
    
    std::cout << "\n╔══════════════════════════════════════════════════════════════════╗\n";
    std::cout << "║  BENCHMARK RESULTS - " << test_type << " test (N=" << display_batch_size << ")";
    std::cout << std::string(71 - test_type.length() - std::to_string(display_batch_size).length() - 20, ' ') << "║\n";
    std::cout << "╚══════════════════════════════════════════════════════════════════╝\n\n";
    
    std::cout << "WALL-CLOCK TIME:\n";
    std::cout << "  Min:      " << std::setw(12) << min_time << " µs\n";
    std::cout << "  Median:   " << std::setw(12) << median_time << " µs  ⭐\n";
    std::cout << "  Mean:     " << std::setw(12) << mean_time << " µs\n";
    std::cout << "  Max:      " << std::setw(12) << max_time << " µs\n";
    std::cout << "  Stddev:   " << std::setw(12) << std::fixed << std::setprecision(2) << stddev << " µs\n";
    std::cout << "  CV:       " << std::setw(12) << std::fixed << std::setprecision(2) << cv << " %\n\n";
    
    // Benchmark quality assessment
    if (cv < 3.0) {
        std::cout << "BENCHMARK QUALITY: ✅ EXCELLENT (CV < 3%)\n";
    } else if (cv < 5.0) {
        std::cout << "BENCHMARK QUALITY: ✅ GOOD (CV < 5%)\n";
    } else if (cv < 10.0) {
        std::cout << "BENCHMARK QUALITY: ⚠️  MODERATE (CV 5-10%)\n";
    } else {
        std::cout << "BENCHMARK QUALITY: ❌ NOISY (CV > 10%)\n";
    }
    std::cout << "\n";
    
        // Final detailed run for per-lane analysis
    std::cout << "\n=== Running final detailed analysis ===\n";
    auto start_final = std::chrono::high_resolution_clock::now();
    
    if (test_type == "insert") {
        if (use_ispc) {
            ispc::userMention_flat_batch(*ispc_map,
                                         usernames_flat.data(),
                                         start_idx.data(),
                                         num_per_post.data(),
                                         postIDs.data(),
                                         batch_size,
                                         lane_start_times.data(),
                                         lane_end_times.data(),
                                         global_start_time);
        } else {
            mt::userMention_flat_batch(*mt_map,
                                       usernames_flat.data(),
                                       start_idx.data(),
                                       num_per_post.data(),
                                       postIDs.data(),
                                       batch_size,
                                       lane_start_times.data(),
                                       lane_end_times.data(),
                                       global_start_time,
                                       num_threads);
        }
    } else {  // lookup
        if (use_ispc) {
            ispc::getMentionNotifications_batch(*ispc_map,
                                                query_flat.data(),
                                                lookup_queries,
                                                results.data(),
                                                MAX_RESULTS,
                                                counts.data(),
                                                lane_start_times.data(),
                                                lane_end_times.data(),
                                                global_start_time);
        } else {
            mt::getMentionNotifications_batch(*mt_map,
                                             query_flat.data(),
                                             lookup_queries,
                                             results.data(),
                                             MAX_RESULTS,
                                             counts.data(),
                                             lane_start_times.data(),
                                             lane_end_times.data(),
                                             global_start_time,
                                             num_threads);
        }
    }
    
    auto end_final = std::chrono::high_resolution_clock::now();
    auto duration_final = std::chrono::duration_cast<std::chrono::microseconds>(end_final - start_final);
    std::cout << "Final run completed in " << duration_final.count() << " µs\n";

    // Print results based on test type (limit output to prevent segfaults)
    if (test_type == "insert") {
        std::cout << "\n=== NotificationMap contents (first 20 entries) ===\n";
        int next_slot_count = use_ispc ? ispc_map->next_slot : mt_map->next_slot.load();
        int print_limit = std::min(next_slot_count, 20);
        for (int i = 0; i < print_limit; i++) {
            if (use_ispc) {
                std::cout << "[" << i << "] key=" << ispc_map->keys[i]
                          << "  postID=" << ispc_map->values[i] << "\n";
            } else {
                std::cout << "[" << i << "] key=" << mt_map->keys[i]
                          << "  postID=" << mt_map->values[i] << "\n";
            }
        }
        if (next_slot_count > print_limit) {
            std::cout << "... (" << (next_slot_count - print_limit) << " more entries)\n";
        }
        std::cout << "Total entries: " << next_slot_count << "\n";
    } else {  // lookup
        std::cout << "\n=== Lookup Results ===\n";
        for (int i = 0; i < lookup_queries; i++) {
            std::cout << "Username " << query_strings[i]
                      << " → " << counts[i] << " posts\n";

            for (int j = 0; j < counts[i]; j++) {
                std::cout << "   postID = "
                          << results[i * MAX_RESULTS + j] << "\n";
            }
            std::cout << "-----------------------------------\n";
        }
    }

    // ------------------------------------------------------------------
    // Step 3: Prepare lookup queries (already declared at top of function)
    // ------------------------------------------------------------------
    // Reset arrays for use - this is for combined insert+lookup test
    int combined_lookup_queries = 4;
    std::vector<uint8_t> combined_query_flat(combined_lookup_queries * MAX_KEY_LEN);
    std::vector<int64_t> combined_results(combined_lookup_queries * MAX_RESULTS);
    std::vector<int> combined_counts(combined_lookup_queries);
    std::vector<std::string> combined_query_strs(combined_lookup_queries);
    
    // Generate random queries for combined test
    std::srand(123);  // Different seed for variety
    for (int i = 0; i < combined_lookup_queries; i++) {
        // Mix of existing and non-existing users
        if (std::rand() % 4 < 3) {
            int user_id = std::rand() % 1000;
            combined_query_strs[i] = "user_" + std::to_string(user_id);
        } else {
            int user_id = 1000 + (std::rand() % 100);
            combined_query_strs[i] = "user_" + std::to_string(user_id);
        }
        strncpy((char*)&combined_query_flat[i * MAX_KEY_LEN], combined_query_strs[i].c_str(), MAX_KEY_LEN - 1);
        combined_query_flat[i * MAX_KEY_LEN + MAX_KEY_LEN - 1] = '\0';
    }

    // ------------------------------------------------------------------
    // Step 4: WARM-UP PHASE for lookup
    // ------------------------------------------------------------------
    // Timing arrays for lookup
    std::vector<int64_t> lane_start_lookup(combined_lookup_queries);
    std::vector<int64_t> lane_end_lookup(combined_lookup_queries);
    int64_t global_start_lookup = 0;
    
    std::cout << "\n🔥 Warming up lookups: " << warmup_iters << " iterations...\n";
    for (int w = 0; w < warmup_iters; w++) {
        if (use_ispc) {
            ispc::getMentionNotifications_batch(*ispc_map,
                                                combined_query_flat.data(),
                                                combined_lookup_queries,
                                                combined_results.data(),
                                                MAX_RESULTS,
                                                combined_counts.data(),
                                                lane_start_lookup.data(),
                                                lane_end_lookup.data(),
                                                global_start_lookup);
        } else {
            mt::getMentionNotifications_batch(*mt_map,
                                             combined_query_flat.data(),
                                             combined_lookup_queries,
                                             combined_results.data(),
                                             MAX_RESULTS,
                                             combined_counts.data(),
                                             lane_start_lookup.data(),
                                             lane_end_lookup.data(),
                                             global_start_lookup,
                                             num_threads);
        }
    }
    std::cout << "✅ Lookup warm-up complete\n\n";

    // ------------------------------------------------------------------
    // Step 5: BENCHMARK PHASE for lookup
    // ------------------------------------------------------------------
    std::cout << "📊 Benchmarking lookups: " << bench_iters << " iterations...\n";
    std::vector<int64_t> time_measurements_lookup_us;
    
    for (int iter = 0; iter < bench_iters; iter++) {
        auto start_lookup = std::chrono::high_resolution_clock::now();
        
        if (use_ispc) {
            ispc::getMentionNotifications_batch(*ispc_map,
                                                combined_query_flat.data(),
                                                combined_lookup_queries,
                                                combined_results.data(),
                                                MAX_RESULTS,
                                                combined_counts.data(),
                                                lane_start_lookup.data(),
                                                lane_end_lookup.data(),
                                                global_start_lookup);
        } else {
            mt::getMentionNotifications_batch(*mt_map,
                                             combined_query_flat.data(),
                                             combined_lookup_queries,
                                             combined_results.data(),
                                             MAX_RESULTS,
                                             combined_counts.data(),
                                             lane_start_lookup.data(),
                                             lane_end_lookup.data(),
                                             global_start_lookup,
                                             num_threads);
        }
        
        auto end_lookup = std::chrono::high_resolution_clock::now();
        auto duration = std::chrono::duration_cast<std::chrono::microseconds>(end_lookup - start_lookup);
        time_measurements_lookup_us.push_back(duration.count());
        
        // Progress indicator
        if (bench_iters >= 20 && (iter + 1) % (bench_iters / 10) == 0) {
            std::cout << "  Progress: " << (iter + 1) << "/" << bench_iters << "\n";
        }
    }
    std::cout << "✅ Lookup benchmarking complete\n\n";
    
    // Calculate statistics
    std::sort(time_measurements_lookup_us.begin(), time_measurements_lookup_us.end());
    int64_t min_time_lookup = time_measurements_lookup_us.front();
    int64_t max_time_lookup = time_measurements_lookup_us.back();
    int64_t median_time_lookup = time_measurements_lookup_us[bench_iters / 2];
    int64_t mean_time_lookup = 0;
    for (auto t : time_measurements_lookup_us) mean_time_lookup += t;
    mean_time_lookup /= bench_iters;
    
    double stddev_lookup = 0;
    for (auto t : time_measurements_lookup_us) {
        stddev_lookup += (t - mean_time_lookup) * (t - mean_time_lookup);
    }
    stddev_lookup = std::sqrt(stddev_lookup / bench_iters);
    double cv_lookup = (stddev_lookup / mean_time_lookup) * 100.0;
    
    std::cout << "\n╔══════════════════════════════════════════════════════════════════╗\n";
    std::cout << "║  BENCHMARK RESULTS - getMentionNotifications_batch (N=" << combined_lookup_queries << ")   ║\n";
    std::cout << "╚══════════════════════════════════════════════════════════════════╝\n\n";
    
    std::cout << "WALL-CLOCK TIME:\n";
    std::cout << "  Min:      " << std::setw(12) << min_time_lookup << " µs\n";
    std::cout << "  Median:   " << std::setw(12) << median_time_lookup << " µs  ⭐\n";
    std::cout << "  Mean:     " << std::setw(12) << mean_time_lookup << " µs\n";
    std::cout << "  Max:      " << std::setw(12) << max_time_lookup << " µs\n";
    std::cout << "  Stddev:   " << std::setw(12) << std::fixed << std::setprecision(2) << stddev_lookup << " µs\n";
    std::cout << "  CV:       " << std::setw(12) << std::fixed << std::setprecision(2) << cv_lookup << " %\n\n";
    
    // Benchmark quality assessment
    if (cv_lookup < 3.0) {
        std::cout << "BENCHMARK QUALITY: ✅ EXCELLENT (CV < 3%)\n";
    } else if (cv_lookup < 5.0) {
        std::cout << "BENCHMARK QUALITY: ✅ GOOD (CV < 5%)\n";
    } else if (cv_lookup < 10.0) {
        std::cout << "BENCHMARK QUALITY: ⚠️  MODERATE (CV 5-10%)\n";
    } else {
        std::cout << "BENCHMARK QUALITY: ❌ NOISY (CV > 10%)\n";
    }
    std::cout << "\n";
    
    // Final detailed run for per-lane analysis
    std::cout << "\n=== Running final detailed lookup analysis ===\n";
    auto start_final_lookup = std::chrono::high_resolution_clock::now();
    
    if (use_ispc) {
        ispc::getMentionNotifications_batch(*ispc_map,
                                            combined_query_flat.data(),
                                            combined_lookup_queries,
                                            combined_results.data(),
                                            MAX_RESULTS,
                                            combined_counts.data(),
                                            lane_start_lookup.data(),
                                            lane_end_lookup.data(),
                                            global_start_lookup);
    } else {
        mt::getMentionNotifications_batch(*mt_map,
                                         combined_query_flat.data(),
                                         combined_lookup_queries,
                                         combined_results.data(),
                                         MAX_RESULTS,
                                         combined_counts.data(),
                                         lane_start_lookup.data(),
                                         lane_end_lookup.data(),
                                         global_start_lookup,
                                         num_threads);
    }
    
    auto end_final_lookup = std::chrono::high_resolution_clock::now();
    auto duration_lookup = std::chrono::duration_cast<std::chrono::microseconds>(end_final_lookup - start_final_lookup);
    std::cout << "Final lookup run completed in " << duration_lookup.count() << " µs\n";

    // ------------------------------------------------------------------
    // Step 5: Print lookup results (show first 10 queries max)
    // ------------------------------------------------------------------
    std::cout << "\n=== Lookup Results (first " << std::min(10, combined_lookup_queries) << " queries) ===\n";
    for (int i = 0; i < std::min(10, combined_lookup_queries); i++) {
        std::cout << "Username " << combined_query_strs[i]
                  << " → " << combined_counts[i] << " posts";
        if (combined_counts[i] > 0) {
            std::cout << " (showing first " << std::min(3, combined_counts[i]) << "):\n";
            for (int j = 0; j < std::min(3, combined_counts[i]); j++) {
                std::cout << "   postID = "
                          << combined_results[i * MAX_RESULTS + j] << "\n";
            }
        } else {
            std::cout << "\n";
        }
        std::cout << "-----------------------------------\n";
    }

    // ------------------------------------------------------------------
    // TIMING ANALYSIS
    // ------------------------------------------------------------------
    int timing_batch = (test_type == "insert") ? batch_size : lookup_queries;
    std::cout << "\n╔══════════════════════════════════════════════════════════════════╗\n";
    std::cout << "║       TIMING ANALYSIS - " << test_type << " test (N=" << timing_batch << ")";
    std::cout << std::string(71 - test_type.length() - std::to_string(timing_batch).length() - 26, ' ') << "║\n";
    std::cout << "╚══════════════════════════════════════════════════════════════════╝\n\n";
    
    std::cout << "Per-Lane Timing (cycles):\n";
    
    if (test_type == "insert") {
        std::cout << "Lane | PostID | #Users | Queue Delay | Exec Time  | Total Latency\n";
        std::cout << "-----+--------+--------+-------------+------------+--------------\n";
        
        for (int i = 0; i < batch_size; i++) {
            int64_t queue_delay = lane_start_times[i] - global_start_time;
            int64_t exec_time = lane_end_times[i] - lane_start_times[i];
            int64_t total_latency = lane_end_times[i] - global_start_time;
            
            std::cout << std::setw(4) << i << " | "
                      << std::setw(6) << postIDs[i] << " | "
                      << std::setw(6) << num_per_post[i] << " | "
                      << std::setw(11) << queue_delay << " | "
                      << std::setw(10) << exec_time << " | "
                      << std::setw(12) << total_latency << "\n";
        }
        
        // Workload analysis for insert
        std::cout << "\n📊 Workload Analysis:\n";
        std::cout << "   Lanes process different #users per post\n";
        for (int i = 0; i < batch_size; i++) {
            int64_t exec_time = lane_end_times[i] - lane_start_times[i];
            std::cout << "      Lane " << i << " (" << num_per_post[i] 
                      << " users): " << exec_time << " cycles\n";
        }
    } else {  // lookup
        std::cout << "Lane | Username | #Found | Queue Delay | Exec Time  | Total Latency\n";
        std::cout << "-----+----------+--------+-------------+------------+--------------\n";
        
        for (int i = 0; i < lookup_queries; i++) {
            int64_t queue_delay = lane_start_times[i] - global_start_time;
            int64_t exec_time = lane_end_times[i] - lane_start_times[i];
            int64_t total_latency = lane_end_times[i] - global_start_time;
            
            std::cout << std::setw(4) << i << " | "
                      << std::setw(8) << query_strings[i] << " | "
                      << std::setw(6) << counts[i] << " | "
                      << std::setw(11) << queue_delay << " | "
                      << std::setw(10) << exec_time << " | "
                      << std::setw(12) << total_latency << "\n";
        }
        
        // Workload analysis for lookup
        std::cout << "\n📊 Workload Analysis:\n";
        std::cout << "   Different result set sizes\n";
        for (int i = 0; i < lookup_queries; i++) {
            int64_t exec_time = lane_end_times[i] - lane_start_times[i];
            std::cout << "      Lane " << i << " ('" << query_strings[i] 
                      << "', " << counts[i] << " posts): " << exec_time << " cycles\n";
        }
    }

    // ------------------------------------------------------------------
    // DUMP TIMING DATA TO CSV
    // ------------------------------------------------------------------
    std::string technique = use_ispc ? "ispc" : ("mt" + std::to_string(num_threads > 0 ? num_threads : 8) + "_" + mt_mode);
    std::string timing_filename = "timing_stats_" + test_type + "_" + technique + ".csv";
    
    FILE* csv_file = fopen(timing_filename.c_str(), "w");
    if (csv_file) {
        // Write header
        fprintf(csv_file, "TestType,Lane,QueueingDelay,ExecutionTime,TotalLatency\n");
        
        // Write averaged timing data based on test type
        int csv_size = (test_type == "insert") ? batch_size : lookup_queries;
        for (int i = 0; i < csv_size; i++) {
            fprintf(csv_file, "%s,%d,%.1f,%.1f,%.1f\n", test_type.c_str(), i, 
                    avg_queue_delay[i], avg_exec_time[i], avg_total_latency[i]);
        }
        
        fclose(csv_file);
        std::cout << "\n✅ Timing data exported to '" << timing_filename << "'\n";
    } else {
        std::cerr << "\n❌ Failed to create CSV file\n";
    }
    
    // ------------------------------------------------------------------
    // DUMP THROUGHPUT STATS TO CSV
    // ------------------------------------------------------------------
    std::string throughput_filename = "throughput_stats_" + test_type + "_" + technique + ".csv";
    
    FILE* throughput_file = fopen(throughput_filename.c_str(), "w");
    if (throughput_file) {
        // Write header
        fprintf(throughput_file, "TestType,Metric,Value,Unit\n");
        fprintf(throughput_file, "%s,Mode,%s,string\n", test_type.c_str(), mode_name.c_str());
        fprintf(throughput_file, "%s,BatchSize,%d,requests\n", test_type.c_str(), batch_size);
        
        // Performance metrics
        double throughput = (batch_size * 1000000.0 / median_time);
        fprintf(throughput_file, "%s,MedianTime,%ld,microseconds\n", test_type.c_str(), median_time);
        fprintf(throughput_file, "%s,Throughput,%.2f,ops/sec\n", test_type.c_str(), throughput);
        fprintf(throughput_file, "%s,AvgLatency,%.2f,nanoseconds\n", test_type.c_str(), (median_time * 1000.0 / batch_size));
        
        // Per-lane averaged statistics
        fprintf(throughput_file, "\nTestType,Lane,AvgQueueDelay,AvgExecTime,AvgTotalLatency,Unit\n");
        
        int throughput_size = (test_type == "insert") ? batch_size : lookup_queries;
        for (int i = 0; i < throughput_size; i++) {
            fprintf(throughput_file, "%s,%d,%.1f,%.1f,%.1f,cycles\n", test_type.c_str(), i, 
                    avg_queue_delay[i], avg_exec_time[i], avg_total_latency[i]);
        }
        
        // Workload analysis (conditional)
        if (test_type == "insert") {
            fprintf(throughput_file, "\nTestType,Lane,Workload,AvgExecTime,Unit\n");
            for (int i = 0; i < batch_size; i++) {
                fprintf(throughput_file, "%s,%d,%d,%.1f,cycles\n", test_type.c_str(), i, num_per_post[i], avg_exec_time[i]);
            }
        } else {  // lookup
            fprintf(throughput_file, "\nTestType,Lane,ResultCount,AvgExecTime,Unit\n");
            for (int i = 0; i < lookup_queries; i++) {
                fprintf(throughput_file, "%s,%d,%d,%.1f,cycles\n", test_type.c_str(), i, counts[i], avg_exec_time[i]);
            }
        }
        
        fclose(throughput_file);
        std::cout << "✅ Throughput stats exported to '" << throughput_filename << "'\n";
    } else {
        std::cerr << "❌ Failed to create throughput CSV file\n";
    }
    
    // Export energy measurement results
    std::cout << "\n" << std::string(60, '=') << "\n";
    std::cout << "⚡ Energy Measurement Results\n";
    std::cout << std::string(60, '=') << "\n";
    
    if (test_type == "insert") {
        EnergyMonitor::compute_stats(insert_energy_stats);
        EnergyMonitor::print_stats(insert_energy_stats);
        
        std::string energy_csv = "energy_measurements_insert_" + energy_mode + "_b" + std::to_string(batch_size) + ".csv";
        std::string energy_summary = "energy_summary_insert_" + energy_mode + "_b" + std::to_string(batch_size) + ".csv";
        EnergyMonitor::export_csv({insert_energy_stats}, energy_csv);
        EnergyMonitor::export_summary_csv({insert_energy_stats}, energy_summary);
        std::cout << "✅ Energy data exported to '" << energy_csv << "' and '" << energy_summary << "'\n";
    } else {
        EnergyMonitor::compute_stats(lookup_energy_stats);
        EnergyMonitor::print_stats(lookup_energy_stats);
        
        std::string energy_csv = "energy_measurements_lookup_" + energy_mode + "_q" + std::to_string(lookup_queries) + ".csv";
        std::string energy_summary = "energy_summary_lookup_" + energy_mode + "_q" + std::to_string(lookup_queries) + ".csv";
        EnergyMonitor::export_csv({lookup_energy_stats}, energy_csv);
        EnergyMonitor::export_summary_csv({lookup_energy_stats}, energy_summary);
        std::cout << "✅ Energy data exported to '" << energy_csv << "' and '" << energy_summary << "'\n";
    }
    
    // Cleanup
    if (!use_ispc) {
        std::cout << "\n🔧 Destroying thread pool...\n";
        mt::DestroyThreadPool();
        std::cout << "✅ Cleanup complete\n";
    }
    
    if (ispc_map) {
        delete ispc_map;
    }
    if (mt_map) {
        delete mt_map;
    }

    std::cout << "\nDone.\n";
    return 0;
}
