/*
  Copyright (c) 2010-2025, Intel Corporation
  SPDX-License-Identifier: BSD-3-Clause
*/

#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <algorithm>
#include <string>
#include <vector>
#include <chrono>
#include <mutex>
#include <sstream>
#include <iomanip>
#include <atomic>
#include <arpa/inet.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <signal.h>
#include <unistd.h>
#include <string.h>
using namespace std;

// Include ISPC header (generated by the ISPC compiler)
#include "simple_ispc.h"
using namespace ispc;

#define MAX_LEN 128

u_int16_t HashMacAddressPid(const std::string &mac)
{
  u_int16_t hash = 0;
  std::string mac_pid = mac + std::to_string(getpid());
  for ( unsigned int i = 0; i < mac_pid.size(); i++ ) {
    hash += ( mac[i] << (( i & 1 ) * 8 ));
  }
  return hash;
}

int GetMachineId (std::string *mac_hash) {
  std::string mac;
  int sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_IP );
  if ( sock < 0 ) {
    cout << "Unable to obtain MAC address" <<endl;
    return -1;
  }

  struct ifconf conf{};
  char ifconfbuf[ 128 * sizeof(struct ifreq)  ];
  memset( ifconfbuf, 0, sizeof( ifconfbuf ));
  conf.ifc_buf = ifconfbuf;
  conf.ifc_len = sizeof( ifconfbuf );
  if ( ioctl( sock, SIOCGIFCONF, &conf ))
  {
    cout << "Unable to obtain MAC address";
    return -1;
  }

  struct ifreq* ifr;
  for (
      ifr = conf.ifc_req;
      reinterpret_cast<char *>(ifr) <
          reinterpret_cast<char *>(conf.ifc_req) + conf.ifc_len;
      ifr++) {
    if ( ifr->ifr_addr.sa_data == (ifr+1)->ifr_addr.sa_data ) {
      continue;  // duplicate, skip it
    }

    if ( ioctl( sock, SIOCGIFFLAGS, ifr )) {
      continue;  // failed to get flags, skip it
    }
    if ( ioctl( sock, SIOCGIFHWADDR, ifr ) == 0 ) {
      mac = std::string(ifr->ifr_addr.sa_data);
      if (!mac.empty()) {
        break;
      }
    }
  }
  close(sock);

  std::stringstream stream;
  stream << std::hex << HashMacAddressPid(mac);
  *mac_hash = stream.str();

  if (mac_hash->size() > 3) {
    mac_hash->erase(0, mac_hash->size() - 3);
  } else if (mac_hash->size() < 3) {
    *mac_hash = std::string(3 - mac_hash->size(), '0') + *mac_hash;
  }
  return 0;
}
//------------------------------------------------------------------------------
// Main
//------------------------------------------------------------------------------

#include <iostream>
#include <cstring>
#include <string>
#include <iostream>
#include <cstring>
#include <string>

int main() {
    // ------------------------------------------------------------------
    // Get machine ID
    // ------------------------------------------------------------------
    std::string machine_id;
    if (GetMachineId(&machine_id) != 0) {
        exit(EXIT_FAILURE);
    }
    std::cout << "Machine ID: " << machine_id << std::endl;

    const char *machine_id_cstr = machine_id.c_str();
    int machine_len = strlen(machine_id_cstr);

    constexpr int STRIDE = 32;
    const int N = 4;

    // ------------------------------------------------------------------
    // Prepare first batch (unique usernames)
    // ------------------------------------------------------------------
    char fn_buf[N * STRIDE] = {};
    char ln_buf[N * STRIDE] = {};
    char un_buf[N * STRIDE] = {};
    char pw_buf[N * STRIDE] = {};
    char bd_buf[N * STRIDE] = {};

    const char* fn[] = {"AA", "B", "C", "D"};
    const char* ln[] = {"A", "B", "C", "D"};
    const char* un[] = {"alice1", "bob2", "charlie3", "diana4"};
    const char* pw[] = {"pass12", "pass2", "pass3", "pass411"};
    const char* bd[] = {"2000-01-01", "1999-03-02", "2001-05-10", "1998-07-07"};

    for (int i = 0; i < N; i++) {
        strcpy(&fn_buf[i * STRIDE], fn[i]);
        strcpy(&ln_buf[i * STRIDE], ln[i]);
        strcpy(&un_buf[i * STRIDE], un[i]);
        strcpy(&pw_buf[i * STRIDE], pw[i]);
        strcpy(&bd_buf[i * STRIDE], bd[i]);
    }

    // ------------------------------------------------------------------
    // Initialize map and user array
    // ------------------------------------------------------------------
    UserMap map{};
    map.count = 0;
    User users[N];

    // ------------------------------------------------------------------
    // First batch: all new users should succeed
    // ------------------------------------------------------------------
    std::cout << "\n=== First insertion batch ===\n";
    ispc::newUser_batch(N,
                        (uint8_t*)machine_id_cstr,
                        machine_len,
                        (uint8_t*)fn_buf,
                        (uint8_t*)ln_buf,
                        (uint8_t*)un_buf,
                        (uint8_t*)pw_buf,
                        (uint8_t*)bd_buf,
                        users,
                        map);
                            std::cout << "Total entries: " << map.count << "\n\n";

    for (int i = 0; i < map.count; i++) {
        std::cout << "User " << i << ":\n"
                  << "  username: " << map.usernames[i] << "\n"
                  << "  first:    " << map.users[i].first_name << "\n"
                  << "  last:     " << map.users[i].last_name << "\n"
                  << "  password: " << map.users[i].password_hashed << "\n"
                  << "  birth:    " << map.users[i].date_birth << "\n"
                  << "  ID:       " << map.users[i].user_id << "\n"
                  << "-------------------------------------\n";
    }


    // ------------------------------------------------------------------
    // Second batch: reuse some usernames (duplicates) + some new ones
    // ------------------------------------------------------------------
    const char* un2[] = {"alice1", "bob2", "new_user1", "new_user2"};
    for (int i = 0; i < N; i++) {
        strcpy(&un_buf[i * STRIDE], un2[i]);
    }

    std::cout << "\n=== Second insertion batch ===\n";
    ispc::newUser_batch(N,
                        (uint8_t*)machine_id_cstr,
                        machine_len,
                        (uint8_t*)fn_buf,
                        (uint8_t*)ln_buf,
                        (uint8_t*)un_buf,
                        (uint8_t*)pw_buf,
                        (uint8_t*)bd_buf,
                        users,
                        map);

    // ------------------------------------------------------------------
    // Print final contents of map
    // ------------------------------------------------------------------
    std::cout << "\n=== Final UserMap contents ===\n";
    std::cout << "Total entries: " << map.count << "\n\n";

    for (int i = 0; i < map.count; i++) {
        std::cout << "User " << i << ":\n"
                  << "  username: " << map.usernames[i] << "\n"
                  << "  first:    " << map.users[i].first_name << "\n"
                  << "  last:     " << map.users[i].last_name << "\n"
                  << "  password: " << map.users[i].password_hashed << "\n"
                  << "  birth:    " << map.users[i].date_birth << "\n"
                  << "  ID:       " << map.users[i].user_id << "\n"
                  << "-------------------------------------\n";
    }

    // ------------------------------------------------------------------
    // LOGIN TESTS
    // ------------------------------------------------------------------
    int results[4] = {0};

    // 4 scenarios: correct, wrong password, new user ok, nonexistent
    const char* test_usernames[] = {"alice1", "bob2", "new_user1", "ghost"};
    const char* test_passwords[] = {"pass12", "wrong_pw", "pass3", "nothing"};

    // login phase buffers
    char login_un_buf[4 * STRIDE] = {};
    char login_pw_buf[4 * STRIDE] = {};

    for (int i = 0; i < 4; i++) {
        strcpy(&login_un_buf[i * STRIDE], test_usernames[i]);
        strcpy(&login_pw_buf[i * STRIDE], test_passwords[i]);
    }

    std::cout << "\n=== Login attempts ===\n";
    ispc::login_batch(map,
                      (uint8_t*)login_un_buf,
                      (uint8_t*)login_pw_buf,
                      4,
                      
                      results);

    // ------------------------------------------------------------------
    // Print login results
    // ------------------------------------------------------------------
    for (int i = 0; i < 4; i++) {
        std::cout << "Login " << test_usernames[i] << " → "
                  << (results[i] ? "✅ success" : "❌ failed") << std::endl;
    }

    std::cout << "\nDone.\n";
    return 0;
}
