/*
  Copyright (c) 2010-2025, Intel Corporation
  SPDX-License-Identifier: BSD-3-Clause
*/

#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <algorithm>
#include <string>
#include <vector>
#include <chrono>
#include <mutex>
#include <sstream>
#include <iomanip>
#include <atomic>
#include <arpa/inet.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <signal.h>
#include <unistd.h>
#include <string.h>
#include <ctime>
#include <cstdlib>
using namespace std;

// Include ISPC header (generated by the ISPC compiler)
#include "simple_ispc.h"
// Include the multithreaded version
#include "simple_mt.h"
using namespace ispc;

#define MAX_LEN 128

u_int16_t HashMacAddressPid(const std::string &mac)
{
  u_int16_t hash = 0;
  std::string mac_pid = mac + std::to_string(getpid());
  for ( unsigned int i = 0; i < mac_pid.size(); i++ ) {
    hash += ( mac[i] << (( i & 1 ) * 8 ));
  }
  return hash;
}

int GetMachineId (std::string *mac_hash) {
  std::string mac;
  int sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_IP );
  if ( sock < 0 ) {
    cout << "Unable to obtain MAC address" <<endl;
    return -1;
  }

  struct ifconf conf{};
  char ifconfbuf[ 128 * sizeof(struct ifreq)  ];
  memset( ifconfbuf, 0, sizeof( ifconfbuf ));
  conf.ifc_buf = ifconfbuf;
  conf.ifc_len = sizeof( ifconfbuf );
  if ( ioctl( sock, SIOCGIFCONF, &conf ))
  {
    cout << "Unable to obtain MAC address";
    return -1;
  }

  struct ifreq* ifr;
  for (
      ifr = conf.ifc_req;
      reinterpret_cast<char *>(ifr) <
          reinterpret_cast<char *>(conf.ifc_req) + conf.ifc_len;
      ifr++) {
    if ( ifr->ifr_addr.sa_data == (ifr+1)->ifr_addr.sa_data ) {
      continue;  // duplicate, skip it
    }

    if ( ioctl( sock, SIOCGIFFLAGS, ifr )) {
      continue;  // failed to get flags, skip it
    }
    if ( ioctl( sock, SIOCGIFHWADDR, ifr ) == 0 ) {
      mac = std::string(ifr->ifr_addr.sa_data);
      if (!mac.empty()) {
        break;
      }
    }
  }
  close(sock);

  std::stringstream stream;
  stream << std::hex << HashMacAddressPid(mac);
  *mac_hash = stream.str();

  if (mac_hash->size() > 3) {
    mac_hash->erase(0, mac_hash->size() - 3);
  } else if (mac_hash->size() < 3) {
    *mac_hash = std::string(3 - mac_hash->size(), '0') + *mac_hash;
  }
  return 0;
}
//------------------------------------------------------------------------------
// Main
//------------------------------------------------------------------------------

#include <iostream>
#include <cstring>
#include <string>
#include <iostream>
#include <cstring>
#include <string>

int main(int argc, char* argv[]) {
    // Parse command-line arguments
    bool use_ispc = true;     // Default to ISPC
    int num_threads = 0;      // 0 means auto-detect for multithreaded
    int N = 4;                // Default number of requests
    double fail_prob = 0.0;   // Default failure probability (0.0 = 0%, 1.0 = 100%)
    std::string test_type = "create";  // Default test type: "create" or "login"
    std::string mt_mode = "pool";      // Default MT mode: "pool" or "spawn"
    int warmup_iters = 5;     // Default warmup iterations
    int bench_iters = 50;     // Default benchmark iterations
    
    if (argc > 1) {
        std::string mode_str = argv[1];
        if (mode_str == "mt" || mode_str == "multithreaded") {
            use_ispc = false;
            if (argc > 2) {
                num_threads = std::atoi(argv[2]);
            }
            if (argc > 3) {
                test_type = argv[3];
            }
            if (argc > 4) {
                mt_mode = argv[4];
            }
            if (argc > 5) {
                N = std::atoi(argv[5]);
            }
            if (argc > 6) {
                fail_prob = std::atof(argv[6]);
            }
            if (argc > 7) {
                bench_iters = std::atoi(argv[7]);
            }
        } else if (mode_str == "ispc") {
            use_ispc = true;
            if (argc > 2) {
                test_type = argv[2];
            }
            if (argc > 3) {
                N = std::atoi(argv[3]);
            }
            if (argc > 4) {
                fail_prob = std::atof(argv[4]);
            }
            if (argc > 5) {
                bench_iters = std::atoi(argv[5]);
            }
        } else {
            std::cerr << "Usage: " << argv[0] << " [mode] [test_type] [num_requests] [fail_prob] [bench_iters]\n";
            std::cerr << "       " << argv[0] << " mt [num_threads] [test_type] [mt_mode] [num_requests] [fail_prob] [bench_iters]\n\n";
            std::cerr << "Arguments:\n";
            std::cerr << "  mode:          'ispc' or 'mt' (multithreaded)\n";
            std::cerr << "  num_threads:   Number of threads (only for mt mode, default=auto)\n";
            std::cerr << "  test_type:     'create' or 'login' (default='create')\n";
            std::cerr << "  mt_mode:       'pool' or 'spawn' (only for mt mode, default='pool')\n";
            std::cerr << "  num_requests:  Number of requests to process (default=4)\n";
            std::cerr << "  fail_prob:     Probability of failure 0.0-1.0 (default=0.0)\n";
            std::cerr << "  bench_iters:   Number of benchmark iterations (default=50)\n";
            std::cerr << "\nExamples:\n";
            std::cerr << "  " << argv[0] << " ispc create 100 0.2      # ISPC, create 100 users, 20% duplicates\n";
            std::cerr << "  " << argv[0] << " ispc login 100 0.3 100   # ISPC, login 100 users, 30% fail, 100 iterations\n";
            std::cerr << "  " << argv[0] << " mt 8 create pool 100 0.25   # MT pool, 8 threads, create 100, 25% fail\n";
            std::cerr << "  " << argv[0] << " mt 8 login spawn 50 0.1 200 # MT spawn, 8 threads, login 50, 10% fail, 200 iterations\n";
            return 1;
        }
    }
    
    // Validate inputs
    if (test_type != "create" && test_type != "login") {
        std::cerr << "Error: test_type must be 'create' or 'login' (got: '" << test_type << "')\n";
        return 1;
    }
    if (mt_mode != "pool" && mt_mode != "spawn") {
        std::cerr << "Error: mt_mode must be 'pool' or 'spawn' (got: '" << mt_mode << "')\n";
        return 1;
    }
    if (fail_prob < 0.0 || fail_prob > 1.0) {
        std::cerr << "Error: fail_prob must be between 0.0 and 1.0 (got: " << fail_prob << ")\n";
        return 1;
    }
    if (N <= 0) {
        std::cerr << "Error: num_requests must be positive\n";
        return 1;
    }
    
    std::string mode_name = use_ispc ? "ISPC SIMD" : ("Multithreaded (" + mt_mode + ")");
    
    std::cout << "\n╔══════════════════════════════════════════════════════════════════╗\n";
    std::cout << "║  USER SERVICE BENCHMARK                                          ║\n";
    std::cout << "╠══════════════════════════════════════════════════════════════════╣\n";
    std::cout << "║  Mode: " << mode_name << std::string(58 - mode_name.length(), ' ') << "║\n";
    std::cout << "║  Test Type: " << test_type << std::string(53 - test_type.length(), ' ') << "║\n";
    std::cout << "║  Batch Size: " << N << std::string(52 - std::to_string(N).length(), ' ') << "║\n";
    if (!use_ispc && num_threads > 0) {
        std::cout << "║  Threads: " << num_threads << std::string(55 - std::to_string(num_threads).length(), ' ') << "║\n";
    } else if (!use_ispc) {
        std::cout << "║  Threads: Auto-detect                                          ║\n";
    }
    std::cout << "║  Warmup Iterations: " << warmup_iters << std::string(45 - std::to_string(warmup_iters).length(), ' ') << "║\n";
    std::cout << "║  Benchmark Iterations: " << bench_iters << std::string(42 - std::to_string(bench_iters).length(), ' ') << "║\n";
    std::cout << "║  Failure Probability: " << (int)(fail_prob * 100) << "%" << std::string(41 - std::to_string((int)(fail_prob * 100)).length(), ' ') << "║\n";
    std::cout << "╚══════════════════════════════════════════════════════════════════╝\n\n";
    
    // Initialize thread pool for multithreaded mode
    ThreadPool::Mode pool_mode = (mt_mode == "spawn") ? ThreadPool::SPAWN_MODE : ThreadPool::POOL_MODE;
    if (!use_ispc) {
        std::cout << "🔧 Initializing thread pool with " 
                  << (num_threads > 0 ? num_threads : std::thread::hardware_concurrency()) 
                  << " threads (" << mt_mode << " mode)...\n";
        mt::InitThreadPool(num_threads, pool_mode);
        std::cout << "✅ Thread pool ready\n\n";
    }
    
    // ------------------------------------------------------------------
    // Get machine ID
    // ------------------------------------------------------------------
    std::string machine_id;
    if (GetMachineId(&machine_id) != 0) {
        exit(EXIT_FAILURE);
    }
    std::cout << "Machine ID: " << machine_id << std::endl;

    const char *machine_id_cstr = machine_id.c_str();
    int machine_len = strlen(machine_id_cstr);

    constexpr int STRIDE = 32;
    
    // Always use SoA for ISPC mode
    bool use_soa = use_ispc;
    if (use_soa) {
        std::cout << "🧪 Using SoA (Structure of Arrays) input layout for ISPC\n";
    }

    // ------------------------------------------------------------------
    // Prepare test data based on test type and failure probability
    // ------------------------------------------------------------------
    std::vector<char> fn_buf(N * STRIDE);
    std::vector<char> ln_buf(N * STRIDE);
    std::vector<char> un_buf(N * STRIDE);
    std::vector<char> pw_buf(N * STRIDE);
    std::vector<char> bd_buf(N * STRIDE);
    
    // SoA buffers (used for ISPC mode)
    std::vector<char> fn_buf_soa(N * STRIDE);
    std::vector<char> ln_buf_soa(N * STRIDE);
    std::vector<char> un_buf_soa(N * STRIDE);
    std::vector<char> pw_buf_soa(N * STRIDE);
    std::vector<char> bd_buf_soa(N * STRIDE);
    
    // Seed random number generator for failure injection
    srand(time(NULL));
    
    // Calculate number of failures to inject
    int num_failures = (int)(N * fail_prob);
    std::vector<bool> should_fail(N, false);
    
    // Randomly select which requests should fail
    if (num_failures > 0) {
        std::vector<int> indices(N);
        for (int i = 0; i < N; i++) indices[i] = i;
        
        // Shuffle and pick first num_failures indices
        for (int i = 0; i < num_failures; i++) {
            int j = i + rand() % (N - i);
            std::swap(indices[i], indices[j]);
            should_fail[indices[i]] = true;
        }
    }
    
    // Generate test data
    for (int i = 0; i < N; i++) {
        snprintf(&fn_buf[i * STRIDE], STRIDE, "First%d", i);
        snprintf(&ln_buf[i * STRIDE], STRIDE, "Last%d", i);
        snprintf(&un_buf[i * STRIDE], STRIDE, "user%d", i);
        snprintf(&pw_buf[i * STRIDE], STRIDE, "pass%d", i);
        snprintf(&bd_buf[i * STRIDE], STRIDE, "2000-01-%02d", (i % 28) + 1);
    }
    
    if (test_type == "create") {
        // For create test: inject duplicate usernames to cause failures
        int duplicate_target = 0;
        for (int i = 0; i < N; i++) {
            if (should_fail[i] && i > 0) {
                // Create duplicate by copying an earlier username
                strcpy(&un_buf[i * STRIDE], &un_buf[duplicate_target * STRIDE]);
                duplicate_target = (duplicate_target + 1) % i;
            }
        }
    }

    // ------------------------------------------------------------------
    // Initialize map and user array
    // ------------------------------------------------------------------
    ispc::UserMap ispc_map{};
    mt::UserMap mt_map{};
    
    if (use_ispc) {
        ispc_map.count = 0;
        // Initialize hash table with -1 (empty)
        for (int i = 0; i < 2048; i++) {
            ispc_map.hashTable[i] = -1;
        }
    } else {
        mt_map.count.store(0);
        // Initialize hash table with -1 (empty)
        for (int i = 0; i < 2048; i++) {
            mt_map.hashTable[i].store(-1, std::memory_order_relaxed);
        }
    }
    
    std::vector<ispc::User> ispc_users(N);
    std::vector<mt::User> mt_users(N);

    // ------------------------------------------------------------------
    // Declare timing variables at function scope
    // ------------------------------------------------------------------
    std::vector<int64_t> lane_start_1(N);
    std::vector<int64_t> lane_end_1(N);
    int64_t global_start_1 = 0;
    
    std::vector<int64_t> lane_start_create(N);
    std::vector<int64_t> lane_end_create(N);
    int64_t global_start_create = 0;
    
    std::vector<int64_t> lane_start_login(N);
    std::vector<int64_t> lane_end_login(N);
    int64_t global_start_login = 0;
    
    // Accumulators for averaging timing across iterations
    std::vector<double> avg_queue_delay_1(N, 0.0);
    std::vector<double> avg_exec_time_1(N, 0.0);
    std::vector<double> avg_total_latency_1(N, 0.0);
    
    std::vector<double> avg_queue_delay_login(N, 0.0);
    std::vector<double> avg_exec_time_login(N, 0.0);
    std::vector<double> avg_total_latency_login(N, 0.0);
    
    std::vector<int> results(N);
    std::vector<int> lane_iterations(N);  // Track iterations per lane for efficiency
    
    // Duration variables
    std::chrono::microseconds duration_1(0);
    std::chrono::microseconds duration_create(0);
    std::chrono::microseconds duration_login(0);
    
    // Result counters
    int total_count_1 = 0;
    int total_users = 0;
    int login_successes = 0;
    int login_failures = 0;
    
    // ------------------------------------------------------------------
    // Convert AoS to SoA if needed
    // ------------------------------------------------------------------
    if (use_soa) {
        std::cout << "🔄 Converting input data from AoS to SoA layout...\n";
        // Convert all fields: AoS[user_i][char_j] -> SoA[char_j][user_i]
        for (int i = 0; i < N; i++) {
            for (int j = 0; j < STRIDE; j++) {
                fn_buf_soa[j * N + i] = fn_buf[i * STRIDE + j];
                ln_buf_soa[j * N + i] = ln_buf[i * STRIDE + j];
                un_buf_soa[j * N + i] = un_buf[i * STRIDE + j];
                pw_buf_soa[j * N + i] = pw_buf[i * STRIDE + j];
                bd_buf_soa[j * N + i] = bd_buf[i * STRIDE + j];
            }
        }
        std::cout << "✅ SoA conversion complete\n";
    }

    // ------------------------------------------------------------------
    // WARMUP PHASE
    // ------------------------------------------------------------------
    std::cout << "🔥 Warming up: " << warmup_iters << " iterations...\n";
    for (int iter = 0; iter < warmup_iters; iter++) {
        // Reset map for each warmup iteration
        if (use_ispc) {
            ispc_map.count = 0;
            // Reset hash table
            for (int i = 0; i < 2048; i++) {
                ispc_map.hashTable[i] = -1;
            }
        } else {
            mt_map.count.store(0);
            // Reset hash table
            for (int i = 0; i < 2048; i++) {
                mt_map.hashTable[i].store(-1, std::memory_order_relaxed);
            }
        }
        
        if (test_type == "create") {
            if (use_ispc) {
                ispc::newUser_batch_soa(N,
                                        (uint8_t*)machine_id_cstr,
                                        machine_len,
                                        (uint8_t*)fn_buf_soa.data(),
                                        (uint8_t*)ln_buf_soa.data(),
                                        (uint8_t*)un_buf_soa.data(),
                                        (uint8_t*)pw_buf_soa.data(),
                                        (uint8_t*)bd_buf_soa.data(),
                                        ispc_users.data(),
                                        ispc_map,
                                        lane_start_1.data(),
                                        lane_end_1.data(),
                                        global_start_1);
            } else {
                mt::newUser_batch(N,
                                 (uint8_t*)machine_id_cstr,
                                 machine_len,
                                 (uint8_t*)fn_buf.data(),
                                 (uint8_t*)ln_buf.data(),
                                 (uint8_t*)un_buf.data(),
                                 (uint8_t*)pw_buf.data(),
                                 (uint8_t*)bd_buf.data(),
                                 mt_users.data(),
                                 mt_map,
                                 lane_start_1.data(),
                                 lane_end_1.data(),
                                 global_start_1,
                                 num_threads);
            }
        } else {
            // For login, we need to pre-populate once in first warmup
            if (iter == 0) {
                int num_unique_users = std::max(10, N / 10);
                std::vector<char> create_un_buf(num_unique_users * STRIDE);
                std::vector<char> create_pw_buf(num_unique_users * STRIDE);
                
                for (int i = 0; i < num_unique_users; i++) {
                    snprintf(&create_un_buf[i * STRIDE], STRIDE, "user%d", i);
                    snprintf(&create_pw_buf[i * STRIDE], STRIDE, "pass%d", i);
                }
                
                // Directly populate map
                if (use_ispc) {
                    for (int i = 0; i < num_unique_users; i++) {
                        // Copy username
                        for (int j = 0; j < STRIDE; j++) {
                            ispc_map.usernames[i][j] = create_un_buf[i * STRIDE + j];
                            if (create_un_buf[i * STRIDE + j] == 0) break;
                        }
                        
                        // Hash the username and populate hash table
                        uint64_t username_hash = 5381ul;
                        for (int j = 0; j < 32; ++j) {
                            uint8_t b = ispc_map.usernames[i][j];
                            if (b == 0) break;
                            username_hash = ((username_hash << 5) + username_hash) + b;
                        }
                        ispc_map.hashValues[i] = username_hash;
                        int hash_idx = (int)(username_hash & (2048 - 1));
                        for (int probe = 0; probe < 8; ++probe) {
                            if (ispc_map.hashTable[hash_idx] == -1) {
                                ispc_map.hashTable[hash_idx] = i;
                                break;
                            }
                            hash_idx = (hash_idx + 1) & (2048 - 1);
                        }
                        
                        // Hash password
                        std::string pass_str(&create_pw_buf[i * STRIDE]);
                        uint64_t h = 1469598103934665603ULL;
                        uint64_t p = 1099511628211ULL;
                        for (char c : pass_str) {
                            h ^= (uint64_t)c;
                            h *= p;
                        }
                        uint64_t x = h;
                        for (int j = 0; j < 64; j++) {
                            if ((j & 7) == 0 && j) x = x * 6364136223846793005ULL + 1ULL;
                            int shift = (j & 7) * 8;
                            int nib = (int)((x >> shift) & 0xF);
                            ispc_map.passwords_hashed[i][j] = (uint8_t)(nib < 10 ? (48 + nib) : (97 + (nib - 10)));
                        }
                        ispc_map.passwords_hashed[i][64] = 0;
                    }
                    ispc_map.count = num_unique_users;
                } else {
                    for (int i = 0; i < num_unique_users; i++) {
                        // Copy username
                        for (int j = 0; j < STRIDE; j++) {
                            mt_map.usernames[i][j] = create_un_buf[i * STRIDE + j];
                            if (create_un_buf[i * STRIDE + j] == 0) break;
                        }
                        
                        // Hash the username and populate hash table
                        uint64_t username_hash = mt::hash_username(&mt_map.usernames[i][0]);
                        mt_map.hashValues[i] = username_hash;
                        int hash_idx = (int)(username_hash & (2048 - 1));
                        for (int probe = 0; probe < 8; ++probe) {
                            int current = mt_map.hashTable[hash_idx].load(std::memory_order_relaxed);
                            if (current == -1) {
                                mt_map.hashTable[hash_idx].store(i, std::memory_order_relaxed);
                                break;
                            }
                            hash_idx = (hash_idx + 1) & (2048 - 1);
                        }
                        
                        // Hash password
                        std::string pass_str(&create_pw_buf[i * STRIDE]);
                        uint64_t h = 1469598103934665603ULL;
                        uint64_t p = 1099511628211ULL;
                        for (char c : pass_str) {
                            h ^= (uint64_t)c;
                            h *= p;
                        }
                        uint64_t x = h;
                        for (int j = 0; j < 64; j++) {
                            if ((j & 7) == 0 && j) x = x * 6364136223846793005ULL + 1ULL;
                            int shift = (j & 7) * 8;
                            int nib = (int)((x >> shift) & 0xF);
                            mt_map.users[i].password_hashed[j] = (uint8_t)(nib < 10 ? (48 + nib) : (97 + (nib - 10)));
                        }
                        mt_map.users[i].password_hashed[64] = 0;
                    }
                    mt_map.count.store(num_unique_users);
                }
            }
            
            // Run login batch
            if (use_ispc) {
                ispc::login_batch_soa(ispc_map,
                                      (uint8_t*)un_buf_soa.data(),
                                      (uint8_t*)pw_buf_soa.data(),
                                      N,
                                      results.data(),
                                      lane_start_login.data(),
                                      lane_end_login.data(),
                                      global_start_login,
                                      lane_iterations.data());
            } else {
                mt::login_batch(mt_map,
                               (uint8_t*)un_buf.data(),
                               (uint8_t*)pw_buf.data(),
                               N,
                               results.data(),
                               lane_start_login.data(),
                               lane_end_login.data(),
                               global_start_login,
                               num_threads);
            }
        }
    }
    std::cout << "✅ Warm-up complete\n\n";
    
    // ------------------------------------------------------------------
    // BENCHMARK PHASE
    // ------------------------------------------------------------------
    std::cout << "📊 Benchmarking: " << bench_iters << " iterations...\n";
    std::vector<int64_t> time_measurements_us;
    
    for (int iter = 0; iter < bench_iters; iter++) {
        // Reset map for each iteration (only for create test, not login)
        if (test_type == "create") {
            if (use_ispc) {
                ispc_map.count = 0;
                // Reset hash table
                for (int i = 0; i < 2048; i++) {
                    ispc_map.hashTable[i] = -1;
                }
            } else {
                mt_map.count.store(0);
                // Reset hash table
                for (int i = 0; i < 2048; i++) {
                    mt_map.hashTable[i].store(-1, std::memory_order_relaxed);
                }
            }
        }
        
        auto start = std::chrono::high_resolution_clock::now();
        
        if (test_type == "create") {
            if (use_ispc) {
                ispc::newUser_batch_soa(N,
                                        (uint8_t*)machine_id_cstr,
                                        machine_len,
                                        (uint8_t*)fn_buf_soa.data(),
                                        (uint8_t*)ln_buf_soa.data(),
                                        (uint8_t*)un_buf_soa.data(),
                                        (uint8_t*)pw_buf_soa.data(),
                                        (uint8_t*)bd_buf_soa.data(),
                                        ispc_users.data(),
                                        ispc_map,
                                        lane_start_1.data(),
                                        lane_end_1.data(),
                                        global_start_1);
            } else {
                mt::newUser_batch(N,
                                 (uint8_t*)machine_id_cstr,
                                 machine_len,
                                 (uint8_t*)fn_buf.data(),
                                 (uint8_t*)ln_buf.data(),
                                 (uint8_t*)un_buf.data(),
                                 (uint8_t*)pw_buf.data(),
                                 (uint8_t*)bd_buf.data(),
                                 mt_users.data(),
                                 mt_map,
                                 lane_start_1.data(),
                                 lane_end_1.data(),
                                 global_start_1,
                                 num_threads);
            }
        } else {
            if (use_ispc) {
                ispc::login_batch_soa(ispc_map,
                                      (uint8_t*)un_buf_soa.data(),
                                      (uint8_t*)pw_buf_soa.data(),
                                      N,
                                      results.data(),
                                      lane_start_login.data(),
                                      lane_end_login.data(),
                                      global_start_login,
                                      lane_iterations.data());
            } else {
                mt::login_batch(mt_map,
                               (uint8_t*)un_buf.data(),
                               (uint8_t*)pw_buf.data(),
                               N,
                               results.data(),
                               lane_start_login.data(),
                               lane_end_login.data(),
                               global_start_login,
                               num_threads);
            }
        }
        
        auto end = std::chrono::high_resolution_clock::now();
        auto duration = std::chrono::duration_cast<std::chrono::microseconds>(end - start);
        time_measurements_us.push_back(duration.count());
        
        // Accumulate relative timing metrics for this iteration
        if (test_type == "create") {
            for (int i = 0; i < N; i++) {
                int64_t queue_delay = lane_start_1[i] - global_start_1;
                int64_t exec_time = lane_end_1[i] - lane_start_1[i];
                int64_t total_latency = lane_end_1[i] - global_start_1;
                
                avg_queue_delay_1[i] += queue_delay;
                avg_exec_time_1[i] += exec_time;
                avg_total_latency_1[i] += total_latency;
            }
        } else {
            for (int i = 0; i < N; i++) {
                int64_t queue_delay = lane_start_login[i] - global_start_login;
                int64_t exec_time = lane_end_login[i] - lane_start_login[i];
                int64_t total_latency = lane_end_login[i] - global_start_login;
                
                avg_queue_delay_login[i] += queue_delay;
                avg_exec_time_login[i] += exec_time;
                avg_total_latency_login[i] += total_latency;
            }
        }
        
        // Progress indicator
        if (bench_iters >= 20 && (iter + 1) % (bench_iters / 10) == 0) {
            std::cout << "  Progress: " << (iter + 1) << "/" << bench_iters << "\n";
        }
    }
    
    // Calculate averages
    if (test_type == "create") {
        for (int i = 0; i < N; i++) {
            avg_queue_delay_1[i] /= bench_iters;
            avg_exec_time_1[i] /= bench_iters;
            avg_total_latency_1[i] /= bench_iters;
        }
    } else {
        for (int i = 0; i < N; i++) {
            avg_queue_delay_login[i] /= bench_iters;
            avg_exec_time_login[i] /= bench_iters;
            avg_total_latency_login[i] /= bench_iters;
        }
    }
    
    std::cout << "✅ Benchmarking complete\n\n";
    
    // Calculate statistics
    std::sort(time_measurements_us.begin(), time_measurements_us.end());
    int64_t min_time = time_measurements_us.front();
    int64_t max_time = time_measurements_us.back();
    int64_t median_time = time_measurements_us[bench_iters / 2];
    int64_t mean_time = 0;
    for (auto t : time_measurements_us) mean_time += t;
    mean_time /= bench_iters;
    
    std::cout << "╔══════════════════════════════════════════════════════════════════╗\n";
    std::cout << "║  BENCHMARK RESULTS - " << test_type << " test (N=" << N << ")";
    std::cout << std::string(71 - test_type.length() - std::to_string(N).length() - 28, ' ') << "║\n";
    std::cout << "╚══════════════════════════════════════════════════════════════════╝\n\n";
    
    std::cout << "WALL-CLOCK TIME:\n";
    std::cout << "  Min:      " << std::setw(12) << min_time << " µs\n";
    std::cout << "  Median:   " << std::setw(12) << median_time << " µs  ⭐\n";
    std::cout << "  Mean:     " << std::setw(12) << mean_time << " µs\n";
    std::cout << "  Max:      " << std::setw(12) << max_time << " µs\n\n";
    
    // ------------------------------------------------------------------
    // Execute test based on test type (for final detailed output)
    // ------------------------------------------------------------------
    
    if (test_type == "create") {
        // ============================================================
        // CREATE USER TEST
        // ============================================================
        std::cout << "\n=== CREATE USER TEST (N=" << N << ", " << (int)(fail_prob * 100) << "% expected failures) ===\n";
        
        auto start_1 = std::chrono::high_resolution_clock::now();
        
        if (use_ispc) {
            ispc::newUser_batch_soa(N,
                                    (uint8_t*)machine_id_cstr,
                                    machine_len,
                                    (uint8_t*)fn_buf_soa.data(),
                                    (uint8_t*)ln_buf_soa.data(),
                                    (uint8_t*)un_buf_soa.data(),
                                    (uint8_t*)pw_buf_soa.data(),
                                    (uint8_t*)bd_buf_soa.data(),
                                    ispc_users.data(),
                                    ispc_map,
                                    lane_start_1.data(),
                                    lane_end_1.data(),
                                    global_start_1);
        } else {
            mt::newUser_batch(N,
                             (uint8_t*)machine_id_cstr,
                             machine_len,
                             (uint8_t*)fn_buf.data(),
                             (uint8_t*)ln_buf.data(),
                             (uint8_t*)un_buf.data(),
                             (uint8_t*)pw_buf.data(),
                             (uint8_t*)bd_buf.data(),
                             mt_users.data(),
                             mt_map,
                             lane_start_1.data(),
                             lane_end_1.data(),
                             global_start_1,
                             num_threads);
        }
        
        auto end_1 = std::chrono::high_resolution_clock::now();
        duration_1 = std::chrono::duration_cast<std::chrono::microseconds>(end_1 - start_1);
        
        total_count_1 = use_ispc ? ispc_map.count : mt_map.count.load();
        
        // Count actual successes and failures
        int successes = total_count_1;
        int actual_failures = N - successes;
        
        std::cout << "\n✅ Test completed in " << duration_1.count() << " µs\n";
        std::cout << "📊 Results:\n";
        std::cout << "   Total requests:    " << N << "\n";
        std::cout << "   Successful:        " << successes << " (" << (100.0 * successes / N) << "%)\n";
        std::cout << "   Failed (dup):      " << actual_failures << " (" << (100.0 * actual_failures / N) << "%)\n";
        std::cout << "   Expected failures: " << num_failures << "\n\n";

        // Print first 10 users
        int print_limit = std::min(10, total_count_1);
        std::cout << "=== Created Users (first " << print_limit << ") ===\n";
        for (int i = 0; i < print_limit; i++) {
            if (use_ispc) {
                std::cout << i << ". " << ispc_map.usernames[i] 
                          << " (ID: " << ispc_map.user_ids[i] << ")\n";
            } else {
                std::cout << i << ". " << mt_map.usernames[i] 
                          << " (ID: " << mt_map.users[i].user_id << ")\n";
            }
        }
        
        if (total_count_1 > 10) {
            std::cout << "... (" << (total_count_1 - 10) << " more users)\n";
        }

    } else {
        // ============================================================
        // LOGIN TEST
        // ============================================================
        std::cout << "\n=== LOGIN TEST (N=" << N << ", " << (int)(fail_prob * 100) << "% expected failures) ===\n";
        
        // STEP 1: Pre-populate map with users (without calling kernels)
        int num_unique_users = std::max(10, N / 10);
        std::cout << "\n[Step 1] Pre-populating map with " << num_unique_users << " unique users for " << N << " login requests...\n";
        
        // Prepare buffers for creating unique users
        std::vector<char> create_fn_buf(num_unique_users * STRIDE);
        std::vector<char> create_ln_buf(num_unique_users * STRIDE);
        std::vector<char> create_un_buf(num_unique_users * STRIDE);
        std::vector<char> create_pw_buf(num_unique_users * STRIDE);
        std::vector<char> create_bd_buf(num_unique_users * STRIDE);
        
        // Generate unique user data
        for (int i = 0; i < num_unique_users; i++) {
            snprintf(&create_fn_buf[i * STRIDE], STRIDE, "First%d", i);
            snprintf(&create_ln_buf[i * STRIDE], STRIDE, "Last%d", i);
            snprintf(&create_un_buf[i * STRIDE], STRIDE, "user%d", i);
            snprintf(&create_pw_buf[i * STRIDE], STRIDE, "pass%d", i);
            snprintf(&create_bd_buf[i * STRIDE], STRIDE, "2000-01-%02d", (i % 28) + 1);
        }
        
        auto start_create = std::chrono::high_resolution_clock::now();
        
        // Directly populate the map without calling the batch creation kernels
        if (use_ispc) {
            // Populate ISPC map directly
            for (int i = 0; i < num_unique_users; i++) {
                // Copy username
                for (int j = 0; j < STRIDE; j++) {
                    ispc_map.usernames[i][j] = create_un_buf[i * STRIDE + j];
                    if (create_un_buf[i * STRIDE + j] == 0) break;
                }
                
                // Copy user fields to SoA arrays
                for (int j = 0; j < STRIDE; j++) {
                    ispc_map.first_names[i][j] = create_fn_buf[i * STRIDE + j];
                    if (create_fn_buf[i * STRIDE + j] == 0) break;
                }
                for (int j = 0; j < STRIDE; j++) {
                    ispc_map.last_names[i][j] = create_ln_buf[i * STRIDE + j];
                    if (create_ln_buf[i * STRIDE + j] == 0) break;
                }
                for (int j = 0; j < STRIDE; j++) {
                    ispc_map.dates_birth[i][j] = create_bd_buf[i * STRIDE + j];
                    if (create_bd_buf[i * STRIDE + j] == 0) break;
                }
                
                // Hash the username and populate hash table
                uint64_t username_hash = 5381ul;
                for (int j = 0; j < 32; ++j) {
                    uint8_t b = ispc_map.usernames[i][j];
                    if (b == 0) break;
                    username_hash = ((username_hash << 5) + username_hash) + b;
                }
                ispc_map.hashValues[i] = username_hash;
                int hash_idx = (int)(username_hash & (2048 - 1));
                for (int probe = 0; probe < 8; ++probe) {
                    if (ispc_map.hashTable[hash_idx] == -1) {
                        ispc_map.hashTable[hash_idx] = i;
                        break;
                    }
                    hash_idx = (hash_idx + 1) & (2048 - 1);
                }
                
                // Hash password and store
                std::string pass_str(&create_pw_buf[i * STRIDE]);
                // Simple hash placeholder (matching the kernel's hash function)
                uint64_t h = 1469598103934665603ULL;
                uint64_t p = 1099511628211ULL;
                for (char c : pass_str) {
                    h ^= (uint64_t)c;
                    h *= p;
                }
                uint64_t x = h;
                for (int j = 0; j < 64; j++) {
                    if ((j & 7) == 0 && j) x = x * 6364136223846793005ULL + 1ULL;
                    int shift = (j & 7) * 8;
                    int nib = (int)((x >> shift) & 0xF);
                    ispc_map.passwords_hashed[i][j] = (uint8_t)(nib < 10 ? (48 + nib) : (97 + (nib - 10)));
                }
                ispc_map.passwords_hashed[i][64] = 0;
                
                // Generate user ID
                ispc_map.user_ids[i] = (int64_t)h;
            }
            ispc_map.count = num_unique_users;
        } else {
            // Populate MT map directly
            for (int i = 0; i < num_unique_users; i++) {
                // Copy username
                for (int j = 0; j < STRIDE; j++) {
                    mt_map.usernames[i][j] = create_un_buf[i * STRIDE + j];
                    if (create_un_buf[i * STRIDE + j] == 0) break;
                }
                
                // Copy user fields
                for (int j = 0; j < STRIDE; j++) {
                    mt_map.users[i].first_name[j] = create_fn_buf[i * STRIDE + j];
                    if (create_fn_buf[i * STRIDE + j] == 0) break;
                }
                for (int j = 0; j < STRIDE; j++) {
                    mt_map.users[i].last_name[j] = create_ln_buf[i * STRIDE + j];
                    if (create_ln_buf[i * STRIDE + j] == 0) break;
                }
                for (int j = 0; j < STRIDE; j++) {
                    mt_map.users[i].username[j] = create_un_buf[i * STRIDE + j];
                    if (create_un_buf[i * STRIDE + j] == 0) break;
                }
                for (int j = 0; j < STRIDE; j++) {
                    mt_map.users[i].date_birth[j] = create_bd_buf[i * STRIDE + j];
                    if (create_bd_buf[i * STRIDE + j] == 0) break;
                }
                
                // Hash the username and populate hash table
                uint64_t username_hash = mt::hash_username(&mt_map.usernames[i][0]);
                mt_map.hashValues[i] = username_hash;
                int hash_idx = (int)(username_hash & (2048 - 1));
                for (int probe = 0; probe < 8; ++probe) {
                    int current = mt_map.hashTable[hash_idx].load(std::memory_order_relaxed);
                    if (current == -1) {
                        mt_map.hashTable[hash_idx].store(i, std::memory_order_relaxed);
                        break;
                    }
                    hash_idx = (hash_idx + 1) & (2048 - 1);
                }
                
                // Hash password and store
                std::string pass_str(&create_pw_buf[i * STRIDE]);
                // Simple hash placeholder (matching the kernel's hash function)
                uint64_t h = 1469598103934665603ULL;
                uint64_t p = 1099511628211ULL;
                for (char c : pass_str) {
                    h ^= (uint64_t)c;
                    h *= p;
                }
                uint64_t x = h;
                for (int j = 0; j < 64; j++) {
                    if ((j & 7) == 0 && j) x = x * 6364136223846793005ULL + 1ULL;
                    int shift = (j & 7) * 8;
                    int nib = (int)((x >> shift) & 0xF);
                    mt_map.users[i].password_hashed[j] = (uint8_t)(nib < 10 ? (48 + nib) : (97 + (nib - 10)));
                }
                mt_map.users[i].password_hashed[64] = 0;
                
                // Generate user ID
                mt_map.users[i].user_id = (int64_t)h;
            }
            mt_map.count.store(num_unique_users);
        }
        
        auto end_create = std::chrono::high_resolution_clock::now();
        duration_create = std::chrono::duration_cast<std::chrono::microseconds>(end_create - start_create);
        
        total_users = use_ispc ? ispc_map.count : mt_map.count.load();
        std::cout << "✅ Pre-populated " << total_users << " unique users in " << duration_create.count() << " µs\n";
        
        // STEP 2: Prepare N login requests (with duplicates) from the created users
        std::cout << "\n[Step 2] Preparing " << N << " login requests (with duplicates allowed)...\n";
        
        std::vector<char> login_un_buf(N * STRIDE);
        std::vector<char> login_pw_buf(N * STRIDE);
        std::vector<char> login_un_buf_soa(N * STRIDE);
        std::vector<char> login_pw_buf_soa(N * STRIDE);
        
        // TEST: Make all requests check the SAME user to test lane efficiency
        const char* TEST_SAME_USER = std::getenv("TEST_SAME_USER");
        bool use_same_user = (TEST_SAME_USER != nullptr);
        
        int num_wrong_pw = 0;
        for (int i = 0; i < N; i++) {
            // Randomly select a user from the created users (allows duplicates)
            int user_idx = use_same_user ? 500 : (rand() % total_users);  // Use user500 for all if testing
            
            // Copy username from the selected user
            strcpy(&login_un_buf[i * STRIDE], &create_un_buf[user_idx * STRIDE]);
            
            // Decide if this login should fail
            if (should_fail[i]) {
                // Use wrong password
                snprintf(&login_pw_buf[i * STRIDE], STRIDE, "wrong_pass%d", i);
                num_wrong_pw++;
            } else {
                // Use correct password from the selected user
                strcpy(&login_pw_buf[i * STRIDE], &create_pw_buf[user_idx * STRIDE]);
            }
        }
        
        // Convert to SoA if needed
        if (use_soa) {
            for (int i = 0; i < N; i++) {
                for (int j = 0; j < STRIDE; j++) {
                    login_un_buf_soa[j * N + i] = login_un_buf[i * STRIDE + j];
                    login_pw_buf_soa[j * N + i] = login_pw_buf[i * STRIDE + j];
                }
            }
        }
        
        if (use_same_user) {
            std::cout << "   🧪 TEST MODE: All requests checking user500\n";
        }
        std::cout << "   Unique users:      " << total_users << "\n";
        std::cout << "   Total requests:    " << N << "\n";
        std::cout << "   Correct passwords: " << (N - num_wrong_pw) << "\n";
        std::cout << "   Wrong passwords:   " << num_wrong_pw << "\n";
        std::cout << "   (Duplicate logins allowed - same user can login multiple times)\n";
        
        // STEP 3: Execute login batch
        std::cout << "\n[Step 3] Executing " << N << " login requests...\n";
        
        auto start_login = std::chrono::high_resolution_clock::now();
        
        if (use_ispc) {
            ispc::login_batch_soa(ispc_map,
                                  (uint8_t*)login_un_buf_soa.data(),
                                  (uint8_t*)login_pw_buf_soa.data(),
                                  N,
                                  results.data(),
                                  lane_start_login.data(),
                                  lane_end_login.data(),
                                  global_start_login,
                                  lane_iterations.data());
        } else {
            mt::login_batch(mt_map,
                           (uint8_t*)login_un_buf.data(),
                           (uint8_t*)login_pw_buf.data(),
                           N,
                           results.data(),
                           lane_start_login.data(),
                           lane_end_login.data(),
                           global_start_login,
                           num_threads);
        }
        
        auto end_login = std::chrono::high_resolution_clock::now();
        duration_login = std::chrono::duration_cast<std::chrono::microseconds>(end_login - start_login);
        
        // Count successes and failures
        login_successes = 0;
        login_failures = 0;
        for (int i = 0; i < N; i++) {
            if (results[i]) login_successes++;
            else login_failures++;
        }
        
        std::cout << "\n✅ Login test completed in " << duration_login.count() << " µs\n";
        std::cout << "📊 Results:\n";
        std::cout << "   Total requests:    " << N << "\n";
        std::cout << "   Successful logins: " << login_successes << " (" << (100.0 * login_successes / N) << "%)\n";
        std::cout << "   Failed logins:     " << login_failures << " (" << (100.0 * login_failures / N) << "%)\n";
        std::cout << "   Expected failures: " << num_failures << "\n";
        
        // Report lane efficiency for ISPC
        if (use_ispc) {
            int64_t total_iterations = 0;
            int64_t max_iterations = 0;
            for (int i = 0; i < N; i++) {
                total_iterations += lane_iterations[i];
                if (lane_iterations[i] > max_iterations) {
                    max_iterations = lane_iterations[i];
                }
            }
            // Efficiency = (useful work) / (total work done by all lanes)
            // In the worst case, all lanes do max_iterations work
            int64_t worst_case_total = N * max_iterations;
            double efficiency = (double)total_iterations / (double)worst_case_total * 100.0;
            
            std::cout << "\n📊 ISPC Lane Efficiency:\n";
            std::cout << "   Total iterations:    " << total_iterations << "\n";
            std::cout << "   Avg iterations/lane: " << (double)total_iterations / N << "\n";
            std::cout << "   Max iterations:      " << max_iterations << "\n";
            std::cout << "   Lane efficiency:     " << std::fixed << std::setprecision(1) << efficiency << "%\n";
            std::cout << "   (Efficiency = avg/max, 100% = all lanes do same work)\n";
        }
        std::cout << "\n";
        
        // Print sample results
        int print_limit = std::min(10, N);
        std::cout << "=== Login Results (first " << print_limit << ") ===\n";
        for (int i = 0; i < print_limit; i++) {
            std::string username(&login_un_buf[i * STRIDE]);
            std::cout << i << ". " << username << " → " 
                      << (results[i] ? "✅ SUCCESS" : "❌ FAILED") << "\n";
        }
        
        if (N > 10) {
            std::cout << "... (" << (N - 10) << " more logins)\n";
        }
    }

    // ------------------------------------------------------------------
    // TIMING ANALYSIS
    // ------------------------------------------------------------------
    std::cout << "\n╔══════════════════════════════════════════════════════════════════╗\n";
    std::cout << "║       TIMING ANALYSIS - " << test_type << " test (N=" << N << ")";
    std::cout << std::string(71 - test_type.length() - std::to_string(N).length() - 28, ' ') << "║\n";
    std::cout << "╚══════════════════════════════════════════════════════════════════╝\n\n";
    
    std::cout << "Per-Lane Timing (cycles):\n";
    std::cout << "Lane | Queueing Delay | Execution Time | Total Latency\n";
    std::cout << "-----+----------------+----------------+--------------\n";
    
    int print_limit = std::min(20, N);
    for (int i = 0; i < print_limit; i++) {
        int64_t queue_delay, exec_time, total_latency;
        
        if (test_type == "create") {
            queue_delay = lane_start_1[i] - global_start_1;
            exec_time = lane_end_1[i] - lane_start_1[i];
            total_latency = lane_end_1[i] - global_start_1;
        } else {
            queue_delay = lane_start_login[i] - global_start_login;
            exec_time = lane_end_login[i] - lane_start_login[i];
            total_latency = lane_end_login[i] - global_start_login;
        }
        
        std::cout << std::setw(4) << i << " | "
                  << std::setw(14) << queue_delay << " | "
                  << std::setw(14) << exec_time << " | "
                  << std::setw(12) << total_latency << "\n";
    }
    
    if (N > 20) {
        std::cout << "... (" << (N - 20) << " more lanes omitted)\n";
    }

    // ------------------------------------------------------------------
    // DUMP TIMING DATA TO CSV
    // ------------------------------------------------------------------
    std::string technique = use_ispc ? "ispc" : ("mt" + std::to_string(num_threads > 0 ? num_threads : 8) + "_" + mt_mode);
    std::string timing_filename = "timing_stats_user_" + technique + "_" + test_type + "_N" + std::to_string(N) + 
                                  "_fail" + std::to_string((int)(fail_prob * 100)) + ".csv";
    
    FILE* csv_file = fopen(timing_filename.c_str(), "w");
    if (csv_file) {
        // Write header
        fprintf(csv_file, "TestType,Lane,QueueingDelay,ExecutionTime,TotalLatency\n");
        
        // Write averaged timing data based on test type
        for (int i = 0; i < N; i++) {
            if (test_type == "create") {
                fprintf(csv_file, "%s,%d,%.1f,%.1f,%.1f\n", test_type.c_str(), i, 
                        avg_queue_delay_1[i], avg_exec_time_1[i], avg_total_latency_1[i]);
            } else {
                fprintf(csv_file, "%s,%d,%.1f,%.1f,%.1f\n", test_type.c_str(), i, 
                        avg_queue_delay_login[i], avg_exec_time_login[i], avg_total_latency_login[i]);
            }
        }
        
        fclose(csv_file);
        std::cout << "\n✅ Timing data exported to '" << timing_filename << "'\n";
    } else {
        std::cerr << "\n❌ Failed to create CSV file\n";
    }
    
    // ------------------------------------------------------------------
    // DUMP THROUGHPUT STATS TO CSV
    // ------------------------------------------------------------------
    std::string throughput_filename = "throughput_stats_user_" + technique + "_" + test_type + "_N" + std::to_string(N) + 
                                      "_fail" + std::to_string((int)(fail_prob * 100)) + ".csv";
    
    FILE* throughput_file = fopen(throughput_filename.c_str(), "w");
    if (throughput_file) {
        // Write header with test configuration
        fprintf(throughput_file, "TestType,Metric,Value,Unit\n");
        fprintf(throughput_file, "%s,Mode,%s,string\n", test_type.c_str(), mode_name.c_str());
        fprintf(throughput_file, "%s,BatchSize,%d,requests\n", test_type.c_str(), N);
        fprintf(throughput_file, "%s,FailureProbability,%.2f,percent\n", test_type.c_str(), fail_prob * 100);
        
        if (test_type == "create") {
            fprintf(throughput_file, "%s,TotalTime,%ld,microseconds\n", test_type.c_str(), duration_1.count());
            double throughput = (N * 1000000.0 / duration_1.count());
            fprintf(throughput_file, "%s,Throughput,%.2f,requests/sec\n", test_type.c_str(), throughput);
            fprintf(throughput_file, "%s,AvgLatencyPerRequest,%.2f,nanoseconds\n", test_type.c_str(), (duration_1.count() * 1000.0 / N));
            fprintf(throughput_file, "%s,SuccessfulCreations,%d,users\n", test_type.c_str(), total_count_1);
            fprintf(throughput_file, "%s,FailedCreations,%d,users\n", test_type.c_str(), N - total_count_1);
        } else {
            fprintf(throughput_file, "%s,CreateTime,%ld,microseconds\n", test_type.c_str(), duration_create.count());
            fprintf(throughput_file, "%s,LoginTime,%ld,microseconds\n", test_type.c_str(), duration_login.count());
            double throughput = (N * 1000000.0 / duration_login.count());
            fprintf(throughput_file, "%s,Throughput,%.2f,logins/sec\n", test_type.c_str(), throughput);
            fprintf(throughput_file, "%s,AvgLatencyPerLogin,%.2f,nanoseconds\n", test_type.c_str(), (duration_login.count() * 1000.0 / N));
            fprintf(throughput_file, "%s,SuccessfulLogins,%d,logins\n", test_type.c_str(), login_successes);
            fprintf(throughput_file, "%s,FailedLogins,%d,logins\n", test_type.c_str(), login_failures);
        }
        
        // Per-lane averaged statistics
        fprintf(throughput_file, "\nTestType,Lane,AvgQueueDelay,AvgExecTime,AvgTotalLatency,Unit\n");
        
        for (int i = 0; i < N; i++) {
            if (test_type == "create") {
                fprintf(throughput_file, "%s,%d,%.1f,%.1f,%.1f,cycles\n", test_type.c_str(), i, 
                        avg_queue_delay_1[i], avg_exec_time_1[i], avg_total_latency_1[i]);
            } else {
                fprintf(throughput_file, "%s,%d,%.1f,%.1f,%.1f,cycles\n", test_type.c_str(), i, 
                        avg_queue_delay_login[i], avg_exec_time_login[i], avg_total_latency_login[i]);
            }
        }
        
        fclose(throughput_file);
        std::cout << "✅ Throughput stats exported to '" << throughput_filename << "'\n";
    } else {
        std::cerr << "❌ Failed to create throughput CSV file\n";
    }

    // Cleanup
    if (!use_ispc) {
        std::cout << "\n🔧 Destroying thread pool...\n";
        mt::DestroyThreadPool();
        std::cout << "✅ Cleanup complete\n";
    }

    std::cout << "\nDone.\n";
    return 0;
}
