/*
  Copyright (c) 2010-2025, Intel Corporation
  SPDX-License-Identifier: BSD-3-Clause
*/

#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <algorithm>
#include <string>
#include <vector>
#include <chrono>
#include <mutex>
#include <sstream>
#include <iomanip>
#include <atomic>
#include <arpa/inet.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <signal.h>
#include <unistd.h>
#include <string.h>
using namespace std;

// Include ISPC header (generated by the ISPC compiler)
#include "simple_ispc.h"
using namespace ispc;

#define MAX_LEN 128

u_int16_t HashMacAddressPid(const std::string &mac)
{
  u_int16_t hash = 0;
  std::string mac_pid = mac + std::to_string(getpid());
  for ( unsigned int i = 0; i < mac_pid.size(); i++ ) {
    hash += ( mac[i] << (( i & 1 ) * 8 ));
  }
  return hash;
}

int GetMachineId (std::string *mac_hash) {
  std::string mac;
  int sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_IP );
  if ( sock < 0 ) {
    cout << "Unable to obtain MAC address" <<endl;
    return -1;
  }

  struct ifconf conf{};
  char ifconfbuf[ 128 * sizeof(struct ifreq)  ];
  memset( ifconfbuf, 0, sizeof( ifconfbuf ));
  conf.ifc_buf = ifconfbuf;
  conf.ifc_len = sizeof( ifconfbuf );
  if ( ioctl( sock, SIOCGIFCONF, &conf ))
  {
    cout << "Unable to obtain MAC address";
    return -1;
  }

  struct ifreq* ifr;
  for (
      ifr = conf.ifc_req;
      reinterpret_cast<char *>(ifr) <
          reinterpret_cast<char *>(conf.ifc_req) + conf.ifc_len;
      ifr++) {
    if ( ifr->ifr_addr.sa_data == (ifr+1)->ifr_addr.sa_data ) {
      continue;  // duplicate, skip it
    }

    if ( ioctl( sock, SIOCGIFFLAGS, ifr )) {
      continue;  // failed to get flags, skip it
    }
    if ( ioctl( sock, SIOCGIFHWADDR, ifr ) == 0 ) {
      mac = std::string(ifr->ifr_addr.sa_data);
      if (!mac.empty()) {
        break;
      }
    }
  }
  close(sock);

  std::stringstream stream;
  stream << std::hex << HashMacAddressPid(mac);
  *mac_hash = stream.str();

  if (mac_hash->size() > 3) {
    mac_hash->erase(0, mac_hash->size() - 3);
  } else if (mac_hash->size() < 3) {
    *mac_hash = std::string(3 - mac_hash->size(), '0') + *mac_hash;
  }
  return 0;
}
//------------------------------------------------------------------------------
// Main
//------------------------------------------------------------------------------

#include <iostream>
#include <cstring>
#include <string>
#include <iostream>
#include <cstring>
#include <string>

int main() {
    // ------------------------------------------------------------------
    // Get machine ID
    // ------------------------------------------------------------------
    std::string machine_id;
    if (GetMachineId(&machine_id) != 0) {
        exit(EXIT_FAILURE);
    }
    std::cout << "Machine ID: " << machine_id << std::endl;

    const char *machine_id_cstr = machine_id.c_str();
    int machine_len = strlen(machine_id_cstr);

    constexpr int STRIDE = 32;
    const int N = 4;

    // ------------------------------------------------------------------
    // Prepare first batch (unique usernames)
    // ------------------------------------------------------------------
    char fn_buf[N * STRIDE] = {};
    char ln_buf[N * STRIDE] = {};
    char un_buf[N * STRIDE] = {};
    char pw_buf[N * STRIDE] = {};
    char bd_buf[N * STRIDE] = {};

    const char* fn[] = {"AA", "B", "C", "D"};
    const char* ln[] = {"A", "B", "C", "D"};
    const char* un[] = {"alice1", "bob2", "charlie3", "diana4"};
    const char* pw[] = {"pass12", "pass2", "pass3", "pass411"};
    const char* bd[] = {"2000-01-01", "1999-03-02", "2001-05-10", "1998-07-07"};

    for (int i = 0; i < N; i++) {
        strcpy(&fn_buf[i * STRIDE], fn[i]);
        strcpy(&ln_buf[i * STRIDE], ln[i]);
        strcpy(&un_buf[i * STRIDE], un[i]);
        strcpy(&pw_buf[i * STRIDE], pw[i]);
        strcpy(&bd_buf[i * STRIDE], bd[i]);
    }

    // ------------------------------------------------------------------
    // Initialize map and user array
    // ------------------------------------------------------------------
    UserMap map{};
    map.count = 0;
    User users[N];

    // ------------------------------------------------------------------
    // First batch: all new users should succeed
    // ------------------------------------------------------------------
    std::cout << "\n=== First insertion batch ===\n";
    
    // Timing arrays for first newUser_batch
    std::vector<int64_t> lane_start_1(N);
    std::vector<int64_t> lane_end_1(N);
    int64_t global_start_1 = 0;
    
    auto start_1 = std::chrono::high_resolution_clock::now();
    ispc::newUser_batch(N,
                        (uint8_t*)machine_id_cstr,
                        machine_len,
                        (uint8_t*)fn_buf,
                        (uint8_t*)ln_buf,
                        (uint8_t*)un_buf,
                        (uint8_t*)pw_buf,
                        (uint8_t*)bd_buf,
                        users,
                        map,
                        lane_start_1.data(),
                        lane_end_1.data(),
                        global_start_1);
    auto end_1 = std::chrono::high_resolution_clock::now();
    
    auto duration_1 = std::chrono::duration_cast<std::chrono::microseconds>(end_1 - start_1);
    std::cout << "Batch completed in " << duration_1.count() << " µs\n";
    std::cout << "Total entries: " << map.count << "\n\n";

    for (int i = 0; i < map.count; i++) {
        std::cout << "User " << i << ":\n"
                  << "  username: " << map.usernames[i] << "\n"
                  << "  first:    " << map.users[i].first_name << "\n"
                  << "  last:     " << map.users[i].last_name << "\n"
                  << "  password: " << map.users[i].password_hashed << "\n"
                  << "  birth:    " << map.users[i].date_birth << "\n"
                  << "  ID:       " << map.users[i].user_id << "\n"
                  << "-------------------------------------\n";
    }


    // ------------------------------------------------------------------
    // Second batch: reuse some usernames (duplicates) + some new ones
    // ------------------------------------------------------------------
    const char* un2[] = {"alice1", "bob2", "new_user1", "new_user2"};
    for (int i = 0; i < N; i++) {
        strcpy(&un_buf[i * STRIDE], un2[i]);
    }

    std::cout << "\n=== Second insertion batch ===\n";
    
    // Timing arrays for second newUser_batch
    std::vector<int64_t> lane_start_2(N);
    std::vector<int64_t> lane_end_2(N);
    int64_t global_start_2 = 0;
    
    auto start_2 = std::chrono::high_resolution_clock::now();
    ispc::newUser_batch(N,
                        (uint8_t*)machine_id_cstr,
                        machine_len,
                        (uint8_t*)fn_buf,
                        (uint8_t*)ln_buf,
                        (uint8_t*)un_buf,
                        (uint8_t*)pw_buf,
                        (uint8_t*)bd_buf,
                        users,
                        map,
                        lane_start_2.data(),
                        lane_end_2.data(),
                        global_start_2);
    auto end_2 = std::chrono::high_resolution_clock::now();
    
    auto duration_2 = std::chrono::duration_cast<std::chrono::microseconds>(end_2 - start_2);
    std::cout << "Batch completed in " << duration_2.count() << " µs\n";

    // ------------------------------------------------------------------
    // Print final contents of map
    // ------------------------------------------------------------------
    std::cout << "\n=== Final UserMap contents ===\n";
    std::cout << "Total entries: " << map.count << "\n\n";

    for (int i = 0; i < map.count; i++) {
        std::cout << "User " << i << ":\n"
                  << "  username: " << map.usernames[i] << "\n"
                  << "  first:    " << map.users[i].first_name << "\n"
                  << "  last:     " << map.users[i].last_name << "\n"
                  << "  password: " << map.users[i].password_hashed << "\n"
                  << "  birth:    " << map.users[i].date_birth << "\n"
                  << "  ID:       " << map.users[i].user_id << "\n"
                  << "-------------------------------------\n";
    }

    // ------------------------------------------------------------------
    // LOGIN TESTS
    // ------------------------------------------------------------------
    int results[4] = {0};

    // 4 scenarios: correct, wrong password, new user ok, nonexistent
    const char* test_usernames[] = {"alice1", "bob2", "new_user1", "ghost"};
    const char* test_passwords[] = {"pass12", "wrong_pw", "pass3", "nothing"};

    // login phase buffers
    char login_un_buf[4 * STRIDE] = {};
    char login_pw_buf[4 * STRIDE] = {};

    for (int i = 0; i < 4; i++) {
        strcpy(&login_un_buf[i * STRIDE], test_usernames[i]);
        strcpy(&login_pw_buf[i * STRIDE], test_passwords[i]);
    }

    std::cout << "\n=== Login attempts ===\n";
    
    // Timing arrays for login_batch
    std::vector<int64_t> lane_start_login(4);
    std::vector<int64_t> lane_end_login(4);
    int64_t global_start_login = 0;
    
    auto start_login = std::chrono::high_resolution_clock::now();
    ispc::login_batch(map,
                      (uint8_t*)login_un_buf,
                      (uint8_t*)login_pw_buf,
                      4,
                      results,
                      lane_start_login.data(),
                      lane_end_login.data(),
                      global_start_login);
    auto end_login = std::chrono::high_resolution_clock::now();
    
    auto duration_login = std::chrono::duration_cast<std::chrono::microseconds>(end_login - start_login);
    std::cout << "Login batch completed in " << duration_login.count() << " µs\n";

    // ------------------------------------------------------------------
    // Print login results
    // ------------------------------------------------------------------
    for (int i = 0; i < 4; i++) {
        std::cout << "Login " << test_usernames[i] << " → "
                  << (results[i] ? "✅ success" : "❌ failed") << std::endl;
    }

    // ------------------------------------------------------------------
    // TIMING ANALYSIS - First newUser_batch
    // ------------------------------------------------------------------
    std::cout << "\n╔══════════════════════════════════════════════════════════════════╗\n";
    std::cout << "║       TIMING ANALYSIS - First newUser_batch (N=" << N << ")              ║\n";
    std::cout << "╚══════════════════════════════════════════════════════════════════╝\n\n";
    
    std::cout << "Per-Lane Timing (cycles):\n";
    std::cout << "Lane | Queueing Delay | Execution Time | Total Latency\n";
    std::cout << "-----+----------------+----------------+--------------\n";
    
    for (int i = 0; i < N; i++) {
        int64_t queue_delay = lane_start_1[i] - global_start_1;
        int64_t exec_time = lane_end_1[i] - lane_start_1[i];
        int64_t total_latency = lane_end_1[i] - global_start_1;
        
        std::cout << std::setw(4) << i << " | "
                  << std::setw(14) << queue_delay << " | "
                  << std::setw(14) << exec_time << " | "
                  << std::setw(12) << total_latency << "\n";
    }
    
    // ------------------------------------------------------------------
    // TIMING ANALYSIS - Second newUser_batch
    // ------------------------------------------------------------------
    std::cout << "\n╔══════════════════════════════════════════════════════════════════╗\n";
    std::cout << "║       TIMING ANALYSIS - Second newUser_batch (N=" << N << ")             ║\n";
    std::cout << "╚══════════════════════════════════════════════════════════════════╝\n\n";
    
    std::cout << "Per-Lane Timing (cycles):\n";
    std::cout << "Lane | Queueing Delay | Execution Time | Total Latency\n";
    std::cout << "-----+----------------+----------------+--------------\n";
    
    for (int i = 0; i < N; i++) {
        int64_t queue_delay = lane_start_2[i] - global_start_2;
        int64_t exec_time = lane_end_2[i] - lane_start_2[i];
        int64_t total_latency = lane_end_2[i] - global_start_2;
        
        std::cout << std::setw(4) << i << " | "
                  << std::setw(14) << queue_delay << " | "
                  << std::setw(14) << exec_time << " | "
                  << std::setw(12) << total_latency << "\n";
    }
    
    // ------------------------------------------------------------------
    // TIMING ANALYSIS - login_batch
    // ------------------------------------------------------------------
    std::cout << "\n╔══════════════════════════════════════════════════════════════════╗\n";
    std::cout << "║       TIMING ANALYSIS - login_batch (N=4)                        ║\n";
    std::cout << "╚══════════════════════════════════════════════════════════════════╝\n\n";
    
    std::cout << "Per-Lane Timing (cycles):\n";
    std::cout << "Lane | Username    | Result | Queue Delay | Exec Time  | Total Latency\n";
    std::cout << "-----+-------------+--------+-------------+------------+--------------\n";
    
    for (int i = 0; i < 4; i++) {
        int64_t queue_delay = lane_start_login[i] - global_start_login;
        int64_t exec_time = lane_end_login[i] - lane_start_login[i];
        int64_t total_latency = lane_end_login[i] - global_start_login;
        
        std::cout << std::setw(4) << i << " | "
                  << std::setw(11) << test_usernames[i] << " | "
                  << (results[i] ? "✅ OK " : "❌ FAIL") << " | "
                  << std::setw(11) << queue_delay << " | "
                  << std::setw(10) << exec_time << " | "
                  << std::setw(12) << total_latency << "\n";
    }

    // ------------------------------------------------------------------
    // DUMP TIMING DATA TO CSV
    // ------------------------------------------------------------------
    FILE* csv_file = fopen("timing_stats.csv", "w");
    if (csv_file) {
        // Write header
        fprintf(csv_file, "Operation,Lane,QueueingDelay,ExecutionTime,TotalLatency\n");
        
        // Write first batch timing data
        for (int i = 0; i < N; i++) {
            int64_t queue_delay = lane_start_1[i] - global_start_1;
            int64_t exec_time = lane_end_1[i] - lane_start_1[i];
            int64_t total_latency = lane_end_1[i] - global_start_1;
            
            fprintf(csv_file, "FirstNewUser,%d,%ld,%ld,%ld\n", i, queue_delay, exec_time, total_latency);
        }
        
        // Write second batch timing data
        for (int i = 0; i < N; i++) {
            int64_t queue_delay = lane_start_2[i] - global_start_2;
            int64_t exec_time = lane_end_2[i] - lane_start_2[i];
            int64_t total_latency = lane_end_2[i] - global_start_2;
            
            fprintf(csv_file, "SecondNewUser,%d,%ld,%ld,%ld\n", i, queue_delay, exec_time, total_latency);
        }
        
        // Write login timing data
        for (int i = 0; i < 4; i++) {
            int64_t queue_delay = lane_start_login[i] - global_start_login;
            int64_t exec_time = lane_end_login[i] - lane_start_login[i];
            int64_t total_latency = lane_end_login[i] - global_start_login;
            
            fprintf(csv_file, "Login,%d,%ld,%ld,%ld\n", i, queue_delay, exec_time, total_latency);
        }
        
        fclose(csv_file);
        std::cout << "\n✅ Timing data exported to 'timing_stats.csv'\n";
    } else {
        std::cerr << "\n❌ Failed to create CSV file\n";
    }
    
    // ------------------------------------------------------------------
    // DUMP THROUGHPUT STATS TO CSV
    // ------------------------------------------------------------------
    FILE* throughput_file = fopen("throughput_stats.csv", "w");
    if (throughput_file) {
        // Write header
        fprintf(throughput_file, "Operation,Metric,Value,Unit\n");
        
        // First batch metrics
        double throughput_1 = (N * 1000000.0 / duration_1.count());
        fprintf(throughput_file, "FirstNewUser,BatchSize,%d,users\n", N);
        fprintf(throughput_file, "FirstNewUser,TotalTime,%ld,microseconds\n", duration_1.count());
        fprintf(throughput_file, "FirstNewUser,Throughput,%.2f,users/sec\n", throughput_1);
        fprintf(throughput_file, "FirstNewUser,AvgLatencyPerUser,%.2f,nanoseconds\n", (duration_1.count() * 1000.0 / N));
        
        // Second batch metrics
        double throughput_2 = (N * 1000000.0 / duration_2.count());
        fprintf(throughput_file, "SecondNewUser,BatchSize,%d,users\n", N);
        fprintf(throughput_file, "SecondNewUser,TotalTime,%ld,microseconds\n", duration_2.count());
        fprintf(throughput_file, "SecondNewUser,Throughput,%.2f,users/sec\n", throughput_2);
        fprintf(throughput_file, "SecondNewUser,AvgLatencyPerUser,%.2f,nanoseconds\n", (duration_2.count() * 1000.0 / N));
        
        // Login batch metrics
        double throughput_login = (4 * 1000000.0 / duration_login.count());
        fprintf(throughput_file, "Login,BatchSize,%d,logins\n", 4);
        fprintf(throughput_file, "Login,TotalTime,%ld,microseconds\n", duration_login.count());
        fprintf(throughput_file, "Login,Throughput,%.2f,logins/sec\n", throughput_login);
        fprintf(throughput_file, "Login,AvgLatencyPerLogin,%.2f,nanoseconds\n", (duration_login.count() * 1000.0 / 4));
        
        // Per-lane statistics for each operation
        fprintf(throughput_file, "\nOperation,Lane,AvgQueueDelay,AvgExecTime,AvgTotalLatency,Unit\n");
        
        for (int i = 0; i < N; i++) {
            int64_t queue_delay = lane_start_1[i] - global_start_1;
            int64_t exec_time = lane_end_1[i] - lane_start_1[i];
            int64_t latency = lane_end_1[i] - global_start_1;
            fprintf(throughput_file, "FirstNewUser,%d,%ld,%ld,%ld,cycles\n", i, queue_delay, exec_time, latency);
        }
        
        for (int i = 0; i < N; i++) {
            int64_t queue_delay = lane_start_2[i] - global_start_2;
            int64_t exec_time = lane_end_2[i] - lane_start_2[i];
            int64_t latency = lane_end_2[i] - global_start_2;
            fprintf(throughput_file, "SecondNewUser,%d,%ld,%ld,%ld,cycles\n", i, queue_delay, exec_time, latency);
        }
        
        for (int i = 0; i < 4; i++) {
            int64_t queue_delay = lane_start_login[i] - global_start_login;
            int64_t exec_time = lane_end_login[i] - lane_start_login[i];
            int64_t latency = lane_end_login[i] - global_start_login;
            fprintf(throughput_file, "Login,%d,%ld,%ld,%ld,cycles\n", i, queue_delay, exec_time, latency);
        }
        
        fclose(throughput_file);
        std::cout << "✅ Throughput stats exported to 'throughput_stats.csv'\n";
    } else {
        std::cerr << "❌ Failed to create throughput CSV file\n";
    }

    std::cout << "\nDone.\n";
    return 0;
}
