/*
  Text Processing Service - ISPC Implementation
  Extracts mentions and URLs, shortens URLs
*/

#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <fstream>
#include <sstream>
#include <algorithm>
#include <string>
#include <vector>
#include <chrono>
#include <iomanip>
#include <numeric>
#include <string.h>
using namespace std;

// Include ISPC header (generated by the ISPC compiler)
#include "simple_ispc.h"
using namespace ispc;

constexpr int MAX_TEXT_LEN = 256;

// Helper function to read texts from CSV
vector<string> readTextsFromCSV(const string& filename, int max_lines = -1) {
    vector<string> texts;
    ifstream file(filename);
    
    if (!file.is_open()) {
        cerr << "Error: Could not open file " << filename << endl;
        return texts;
    }
    
    string line;
    int count = 0;
    
    // Skip header if present
    if (getline(file, line)) {
        // Check if first line looks like a header
        if (line.find("status_message") != string::npos || 
            line.find("text") != string::npos) {
            // Skip header
        } else {
            // Not a header, use it as first text
            texts.push_back(line);
            count++;
        }
    }
    
    while (getline(file, line) && (max_lines < 0 || count < max_lines)) {
        if (!line.empty()) {
            texts.push_back(line);
            count++;
        }
    }
    
    file.close();
    return texts;
}

void printResults(const vector<TextResult>& results, 
                  const vector<string>& original_texts,
                  int num_to_show = 3) {
    cout << "\n╔══════════════════════════════════════════════════════════════════╗\n";
    cout << "║                    SAMPLE RESULTS                                ║\n";
    cout << "╚══════════════════════════════════════════════════════════════════╝\n\n";
    
    int to_show = min(num_to_show, (int)results.size());
    
    for (int i = 0; i < to_show; i++) {
        const auto& res = results[i];
        
        cout << "--- Text " << i << " ---\n";
        
        // Show truncated original
        string orig_truncated = original_texts[i].substr(0, 80);
        if (original_texts[i].length() > 80) orig_truncated += "...";
        cout << "Original: " << orig_truncated << "\n";
        
        // Show truncated updated
        string updated_str((char*)res.updated_text);
        string updated_truncated = updated_str.substr(0, 80);
        if (updated_str.length() > 80) updated_truncated += "...";
        cout << "Updated:  " << updated_truncated << "\n";
        
        cout << "Mentions (" << res.num_mentions << "):";
        for (int j = 0; j < res.num_mentions; j++) {
            cout << " @" << (char*)res.mentions[j];
        }
        cout << "\n";
        
        cout << "URLs (" << res.num_urls << "):\n";
        for (int j = 0; j < res.num_urls; j++) {
            cout << "  Original: " << (char*)res.urls[j] << "\n";
            cout << "  Shortened: " << (char*)res.shortened_urls[j] << "\n";
        }
        cout << "\n";
    }
}

void exportTimingStats(const string& filename,
                       const vector<int64_t>& lane_starts,
                       const vector<int64_t>& lane_ends,
                       int64_t global_start) {
    ofstream csv(filename);
    csv << "Operation,Lane,QueueingDelay,ExecutionTime,TotalLatency\n";
    
    for (size_t i = 0; i < lane_starts.size(); i++) {
        int64_t queue_delay = lane_starts[i] - global_start;
        int64_t exec_time = lane_ends[i] - lane_starts[i];
        int64_t total_latency = lane_ends[i] - global_start;
        
        csv << "TextProcessing," << i << "," 
            << queue_delay << "," << exec_time << "," << total_latency << "\n";
    }
    
    csv.close();
}

void exportThroughputStats(const string& filename,
                           int num_texts,
                           double elapsed_us,
                           const vector<int64_t>& lane_starts,
                           const vector<int64_t>& lane_ends,
                           const vector<TextResult>& results) {
    ofstream csv(filename);
    
    // Overall metrics
    double throughput = (num_texts / elapsed_us) * 1e6; // texts/sec
    double avg_latency = (elapsed_us * 1000.0) / num_texts; // ns/text
    
    csv << "Operation,Metric,Value,Unit\n";
    csv << "TextProcessing,BatchSize," << num_texts << ",texts\n";
    csv << "TextProcessing,TotalTime," << (int)elapsed_us << ",microseconds\n";
    csv << "TextProcessing,Throughput," << fixed << setprecision(2) << throughput << ",texts/sec\n";
    csv << "TextProcessing,AvgLatencyPerText," << fixed << setprecision(2) << avg_latency << ",nanoseconds\n";
    csv << "\n";
    
    // Per-lane timing breakdown
    csv << "Operation,Lane,AvgQueueDelay,AvgExecTime,AvgTotalLatency,Unit\n";
    
    int64_t global_start = lane_starts[0];
    for (size_t i = 0; i < lane_starts.size(); i++) {
        int64_t queue_delay = lane_starts[i] - global_start;
        int64_t exec_time = lane_ends[i] - lane_starts[i];
        int64_t total_latency = lane_ends[i] - global_start;
        
        csv << "TextProcessing," << i << "," 
            << queue_delay << "," << exec_time << "," << total_latency << ",cycles\n";
    }
    csv << "\n";
    
    // Per-lane workload
    csv << "Operation,Lane,Mentions,URLs,ExecTime,Unit\n";
    for (size_t i = 0; i < results.size(); i++) {
        int64_t exec_time = lane_ends[i] - lane_starts[i];
        csv << "TextProcessing," << i << "," 
            << results[i].num_mentions << "," << results[i].num_urls << "," 
            << exec_time << ",cycles\n";
    }
    
    csv.close();
}

int main(int argc, char* argv[]) {
    if (argc < 3) {
        cerr << "Usage: " << argv[0] << " <csv_file> <num_lines>\n";
        return 1;
    }
    
    string filename = argv[1];
    int num_lines = atoi(argv[2]);
    
    cout << "Reading texts from file...\n";
    vector<string> texts = readTextsFromCSV(filename, num_lines);
    
    if (texts.empty()) {
        cerr << "No texts loaded!\n";
        return 1;
    }
    
    int N = texts.size();
    cout << "Processing " << N << " texts...\n";
    
    // Flatten texts into byte array
    vector<uint8_t> texts_flat(N * MAX_TEXT_LEN, 0);
    for (int i = 0; i < N; i++) {
        strncpy((char*)&texts_flat[i * MAX_TEXT_LEN], texts[i].c_str(), MAX_TEXT_LEN - 1);
    }
    
    // Prepare output structures
    vector<TextResult> results(N);
    vector<int64_t> lane_start_times(N, 0);
    vector<int64_t> lane_end_times(N, 0);
    int64_t global_start_time = 0;
    
    // Process texts
    cout << "\n=== Processing Texts with ISPC ===\n";
    
    auto start = chrono::high_resolution_clock::now();
    
    ispc::processText_batch(
        texts_flat.data(),
        N,
        results.data(),
        lane_start_times.data(),
        lane_end_times.data(),
        global_start_time
    );
    
    auto end = chrono::high_resolution_clock::now();
    auto elapsed_us = chrono::duration_cast<chrono::microseconds>(end - start).count();
    auto elapsed_ns = chrono::duration_cast<chrono::nanoseconds>(end - start).count();
    
    // Performance stats
    cout << "\n╔══════════════════════════════════════════════════════════════════╗\n";
    cout << "║              TEXT PROCESSING PERFORMANCE                         ║\n";
    cout << "╚══════════════════════════════════════════════════════════════════╝\n\n";
    
    cout << "Texts processed: " << N << "\n";
    cout << "Execution time: " << elapsed_us << " μs (" << elapsed_ns << " ns)\n";
    cout << fixed << setprecision(2);
    cout << "Throughput: " << (N / (elapsed_us / 1e6)) << " texts/sec\n";
    cout << "Average latency: " << (elapsed_ns / (double)N) << " ns/text\n";
    
    // Per-lane timing breakdown
    cout << "\n--- Per-Lane Timing (CPU clock cycles) ---\n";
    cout << "Global start: " << global_start_time << "\n\n";
    cout << "Lane | Queue Delay | Exec Time  | Total Latency | Mentions | URLs\n";
    cout << "-----+-------------+------------+---------------+----------+-----\n";
    
    for (int i = 0; i < min(N, 10); i++) {
        int64_t queue_delay = lane_start_times[i] - global_start_time;
        int64_t exec_time = lane_end_times[i] - lane_start_times[i];
        int64_t total_latency = lane_end_times[i] - global_start_time;
        
        cout << setw(4) << i << " | "
             << setw(11) << queue_delay << " | "
             << setw(10) << exec_time << " | "
             << setw(13) << total_latency << " | "
             << setw(8) << results[i].num_mentions << " | "
             << setw(4) << results[i].num_urls << "\n";
    }
    
    // Timing statistics
    vector<int64_t> total_latencies;
    vector<int64_t> exec_times;
    for (int i = 0; i < N; i++) {
        total_latencies.push_back(lane_end_times[i] - global_start_time);
        exec_times.push_back(lane_end_times[i] - lane_start_times[i]);
    }
    
    auto min_latency = *min_element(total_latencies.begin(), total_latencies.end());
    auto max_latency = *max_element(total_latencies.begin(), total_latencies.end());
    auto avg_latency = accumulate(total_latencies.begin(), total_latencies.end(), 0LL) / N;
    
    auto min_exec = *min_element(exec_times.begin(), exec_times.end());
    auto max_exec = *max_element(exec_times.begin(), exec_times.end());
    auto avg_exec = accumulate(exec_times.begin(), exec_times.end(), 0LL) / N;
    
    cout << "\nTiming Statistics:\n";
    cout << "  Min total latency: " << min_latency << " cycles\n";
    cout << "  Max total latency: " << max_latency << " cycles\n";
    cout << "  Avg total latency: " << fixed << setprecision(2) << (double)avg_latency << " cycles\n";
    cout << "  Min execution: " << min_exec << " cycles\n";
    cout << "  Max execution: " << max_exec << " cycles\n";
    cout << "  Avg execution: " << fixed << setprecision(2) << (double)avg_exec << " cycles\n";
    cout << "  Variation: " << (max_exec - min_exec) << " cycles ("
         << fixed << setprecision(1) << (100.0 * (max_exec - min_exec) / avg_exec) << "% of avg)\n";
    
    // Show sample results
    printResults(results, texts, 3);
    
    // Summary
    cout << "╔══════════════════════════════════════════════════════════════════╗\n";
    cout << "║                    PROCESSING SUMMARY                            ║\n";
    cout << "╚══════════════════════════════════════════════════════════════════╝\n\n";
    
    int total_mentions = 0;
    int total_urls = 0;
    for (const auto& res : results) {
        total_mentions += res.num_mentions;
        total_urls += res.num_urls;
    }
    
    cout << "Total texts processed: " << N << "\n";
    cout << "Total mentions extracted: " << total_mentions 
         << " (avg: " << fixed << setprecision(2) << (total_mentions / (double)N) << " per text)\n";
    cout << "Total URLs extracted: " << total_urls 
         << " (avg: " << fixed << setprecision(2) << (total_urls / (double)N) << " per text)\n";
    cout << "All URLs shortened successfully!\n";
    
    // Export stats
    exportTimingStats("timing_stats.csv", lane_start_times, lane_end_times, global_start_time);
    exportThroughputStats("throughput_stats.csv", N, elapsed_us, 
                         lane_start_times, lane_end_times, results);
    
    cout << "\n✅ Timing data exported to 'timing_stats.csv'\n";
    cout << "✅ Throughput stats exported to 'throughput_stats.csv'\n";
    cout << "\nDone.\n";
    
    return 0;
}
